/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/transactions/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze a transaction */
        post: operations["analyzeTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions */
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transaction by internal id */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rules */
        get: operations["listRules"];
        put?: never;
        /** Create rule */
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get rule */
        get: operations["getRule"];
        /** Update rule */
        put: operations["updateRule"];
        post?: never;
        /** Delete rule */
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle rule enabled */
        patch: operations["toggleRule"];
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit events */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system metrics */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyzeTransactionRequest: {
            workflow?: string;
            recordType?: string;
            dataSpecificationVersion?: number;
            clientIdFromHeader?: string;
            externalTransactionId: string;
            customerIdFromHeader: string;
            /** Format: int64 */
            customerAcctNumber: number;
            /** @description Tokenizado/mascarado; nunca armazenar PAN em claro. */
            pan: string;
            merchantId?: string;
            merchantName?: string;
            transactionAmount: number;
            /** @description YYYYMMDD */
            transactionDate: number;
            /** @description HHMMSS */
            transactionTime: number;
            gmtOffset?: string;
            transactionCurrencyCode: number;
            transactionCurrencyConversionRate?: number;
            merchantCountryCode?: string;
            merchantCity?: string;
            merchantState?: string;
            merchantPostalCode?: string;
            mcc: number;
            posEntryMode?: string;
            customerPresent?: string;
            authPostFlag?: string;
            authDecisionCode?: string;
            authResponseCode?: string;
            authId?: string;
            authIndicator?: number;
            processorAuthReasonCode?: string;
            standinAdvice?: string;
            transactionType?: string;
            transactionCategory?: string;
            consumerAuthenticationScore: number;
            externalScore3: number;
            cavvResult: number;
            cavvKeyIndicator?: number;
            secondFactorAuthCode?: string;
            cryptogramValid?: string;
            cvv2Response?: string;
            cvv2Present?: string;
            pinVerifyCode?: string;
            cvvVerifyCode?: string;
            cvrofflinePinVerificationPerformed?: number;
            cvrofflinePinVerificationFailed?: number;
            cvvPinTryLimitExceeded?: number;
            eciIndicator: number;
            atcCard: number;
            atcHost: number;
            tokenAssuranceLevel: number;
            tokenizationIndicator?: string;
            tokenId?: string;
            tokenRequestorId?: string;
            paymentInstrumentId?: string;
            availableCredit: number;
            cardCashBalance: number;
            cardDelinquentAmount: number;
            cardSeqNum?: number | null;
            cardExpireDate?: number;
            cardMediaType?: string;
            cardAipStatic?: string;
            cardAipDynamic?: string;
            cardAipVerify?: string;
            cardAipRisk?: string;
            cardAipIssuerAuthentication?: string;
            cardAipCombined?: string;
            terminalId?: string;
            terminalType?: string;
            terminalEntryCapability?: string;
            posConditionCode?: string;
            posOffPremises?: number;
            posCardCapture?: number;
            posSecurity?: number;
            terminalVerificationResults?: string;
            cardVerificationResults?: string;
            networkId?: string;
            atmOwner?: string;
            acquirerId?: string;
            acquirerCountry?: string;
            acquirerBin?: string | null;
            expandedBIN?: string;
            tranCode?: string;
            avsRequest?: string;
            checkNumber?: string;
            recordCreationDate?: number;
            recordCreationTime?: number;
            recordCreationMilliseconds?: number;
            portfolio?: string;
            onUsMerchantId?: string;
            userIndicator01?: string;
            userIndicator03?: string;
            userIndicator04?: string;
            userIndicator05?: string;
            userIndicator08?: string;
            idMethod?: number;
            userData01?: string;
            userData02?: string;
            userData03?: string;
            userData04?: string;
            userData05?: string;
            userData06?: string;
            userData06_2?: string;
            userData09?: string;
        };
        TriggeredRule: {
            name: string;
            weight: number;
            contribution: number;
            detail?: string;
        };
        AnalyzeTransactionResponse: {
            transactionId: string;
            /** @enum {string} */
            classification: "APPROVED" | "SUSPICIOUS" | "FRAUD";
            riskScore: number;
            triggeredRules: components["schemas"]["TriggeredRule"][];
            reason: string;
            rulesetVersion: string;
            /** Format: int64 */
            processingTimeMs: number;
            /** Format: date-time */
            timestamp: string;
            success: boolean;
        };
        RuleCondition: {
            field: string;
            /** @enum {string} */
            operator: "==" | "!=" | ">" | "<" | ">=" | "<=" | "IN" | "NOT_IN" | "CONTAINS" | "NOT_CONTAINS";
            value: string;
        };
        Rule: {
            /** Format: int64 */
            id?: number;
            ruleName: string;
            description?: string;
            /** @enum {string} */
            ruleType: "SECURITY" | "CONTEXT" | "VELOCITY" | "ANOMALY";
            weight: number;
            enabled: boolean;
            /** @enum {string} */
            classification: "APPROVED" | "SUSPICIOUS" | "FRAUD";
            conditions: components["schemas"]["RuleCondition"][];
            /** @enum {string} */
            logicOperator: "AND" | "OR";
            version?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AuditLog: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            transactionId?: number;
            actionType?: string;
            description?: string;
            details?: string;
            performedBy?: string;
            result?: string;
            errorMessage?: string;
            sourceIp?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        Metrics: {
            /** Format: int64 */
            totalTransactions?: number;
            /** Format: int64 */
            approvedTransactions?: number;
            /** Format: int64 */
            suspiciousTransactions?: number;
            /** Format: int64 */
            fraudTransactions?: number;
            approvalRate?: number;
            suspiciousRate?: number;
            fraudRate?: number;
            period?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PageAnalyzeTransactionResponse: {
            content?: components["schemas"]["AnalyzeTransactionResponse"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            size?: number;
            number?: number;
        };
        PageRule: {
            content?: components["schemas"]["Rule"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            size?: number;
            number?: number;
        };
        PageAuditLog: {
            content?: components["schemas"]["AuditLog"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            size?: number;
            number?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyzeTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeTransactionRequest"];
            };
        };
        responses: {
            /** @description Analysis result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeTransactionResponse"];
                };
            };
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                customerId?: string;
                merchantId?: string;
                mcc?: number;
                minAmount?: number;
                maxAmount?: number;
                startDate?: string;
                endDate?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnalyzeTransactionResponse"];
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeTransactionResponse"];
                };
            };
        };
    };
    listRules: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageRule"];
                };
            };
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Rule"];
            };
        };
        responses: {
            /** @description Rule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
        };
    };
    getRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Rule"];
            };
        };
        responses: {
            /** @description Rule updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggleRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
        };
    };
    listAudit: {
        parameters: {
            query?: {
                actionType?: string;
                result?: string;
                startDate?: string;
                endDate?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged audit logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAuditLog"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
        };
    };
}
