// Auto-generated from RuleCondition.java - 465 operators (including 18 Neo4j)
// DO NOT EDIT MANUALLY - Run generate_operators.py to update

export interface OperatorDefinition {
  value: string;
  label: string;
  description: string;
  requiresValue?: boolean;
  category?: string;
}

export const OPERATORS: OperatorDefinition[] = [
  { value: 'EQ', label: 'Eq', description: 'Operador Eq', requiresValue: true, category: 'Comparação Básica' },
  { value: 'NEQ', label: 'Neq', description: 'Operador Neq', requiresValue: true, category: 'Comparação Básica' },
  { value: 'GT', label: 'Gt', description: 'Operador Gt', requiresValue: true, category: 'Comparação Básica' },
  { value: 'GTE', label: 'Gte', description: 'Operador Gte', requiresValue: true, category: 'Comparação Básica' },
  { value: 'LT', label: 'Lt', description: 'Operador Lt', requiresValue: true, category: 'Comparação Básica' },
  { value: 'LTE', label: 'Lte', description: 'Operador Lte', requiresValue: true, category: 'Comparação Básica' },
  { value: 'IN', label: 'In', description: 'Operador In', requiresValue: true, category: 'Listas' },
  { value: 'NOT_IN', label: 'Not In', description: 'Operador Not In', requiresValue: true, category: 'Listas' },
  { value: 'CONTAINS', label: 'Contains', description: 'Operador Contains', requiresValue: true, category: 'Strings' },
  { value: 'NOT_CONTAINS', label: 'Not Contains', description: 'Operador Not Contains', requiresValue: true, category: 'Strings' },
  { value: 'STARTS_WITH', label: 'Starts With', description: 'Operador Starts With', requiresValue: true, category: 'Strings' },
  { value: 'ENDS_WITH', label: 'Ends With', description: 'Operador Ends With', requiresValue: true, category: 'Strings' },
  { value: 'REGEX', label: 'Regex', description: 'Operador Regex', requiresValue: true, category: 'Strings' },
  { value: 'NOT_REGEX', label: 'Not Regex', description: 'Operador Not Regex', requiresValue: true, category: 'Strings' },
  { value: 'IS_NULL', label: 'Is Null', description: 'Operador Is Null', requiresValue: false, category: 'Nulos/Booleanos' },
  { value: 'NOT_NULL', label: 'Not Null', description: 'Operador Not Null', requiresValue: false, category: 'Nulos/Booleanos' },
  { value: 'IS_TRUE', label: 'Is True', description: 'Operador Is True', requiresValue: false, category: 'Nulos/Booleanos' },
  { value: 'IS_FALSE', label: 'Is False', description: 'Operador Is False', requiresValue: false, category: 'Nulos/Booleanos' },
  { value: 'BETWEEN', label: 'Between', description: 'Operador Between', requiresValue: true, category: 'Range' },
  { value: 'NOT_BETWEEN', label: 'Not Between', description: 'Operador Not Between', requiresValue: true, category: 'Range' },
  { value: 'FIELD_EQ', label: 'Field Eq', description: 'Operador Field Eq', requiresValue: true, category: 'Comparação entre Campos' },
  { value: 'FIELD_NEQ', label: 'Field Neq', description: 'Operador Field Neq', requiresValue: true, category: 'Comparação entre Campos' },
  { value: 'FIELD_GT', label: 'Field Gt', description: 'Operador Field Gt', requiresValue: true, category: 'Comparação entre Campos' },
  { value: 'FIELD_GTE', label: 'Field Gte', description: 'Operador Field Gte', requiresValue: true, category: 'Comparação entre Campos' },
  { value: 'FIELD_LT', label: 'Field Lt', description: 'Operador Field Lt', requiresValue: true, category: 'Comparação entre Campos' },
  { value: 'FIELD_LTE', label: 'Field Lte', description: 'Operador Field Lte', requiresValue: true, category: 'Comparação entre Campos' },
  { value: 'DATE_BEFORE', label: 'Date Before', description: 'Operador Date Before', requiresValue: true, category: 'Data/Hora' },
  { value: 'DATE_AFTER', label: 'Date After', description: 'Operador Date After', requiresValue: true, category: 'Data/Hora' },
  { value: 'DATE_BETWEEN', label: 'Date Between', description: 'Operador Date Between', requiresValue: true, category: 'Data/Hora' },
  { value: 'TIME_BEFORE', label: 'Time Before', description: 'Operador Time Before', requiresValue: true, category: 'Data/Hora' },
  { value: 'TIME_AFTER', label: 'Time After', description: 'Operador Time After', requiresValue: true, category: 'Data/Hora' },
  { value: 'TIME_BETWEEN', label: 'Time Between', description: 'Operador Time Between', requiresValue: true, category: 'Data/Hora' },
  { value: 'ARRAY_CONTAINS', label: 'Array Contains', description: 'Operador Array Contains', requiresValue: true, category: 'Arrays' },
  { value: 'ARRAY_NOT_CONTAINS', label: 'Array Not Contains', description: 'Operador Array Not Contains', requiresValue: true, category: 'Arrays' },
  { value: 'ARRAY_SIZE_EQ', label: 'Array Size Eq', description: 'Operador Array Size Eq', requiresValue: true, category: 'Arrays' },
  { value: 'ARRAY_SIZE_GT', label: 'Array Size Gt', description: 'Operador Array Size Gt', requiresValue: true, category: 'Arrays' },
  { value: 'ARRAY_SIZE_LT', label: 'Array Size Lt', description: 'Operador Array Size Lt', requiresValue: true, category: 'Arrays' },
  { value: 'MOD_EQ', label: 'Mod Eq', description: 'Operador Mod Eq', requiresValue: true, category: 'Matemáticos' },
  { value: 'MOD_NEQ', label: 'Mod Neq', description: 'Operador Mod Neq', requiresValue: true, category: 'Matemáticos' },
  { value: 'GEO_DISTANCE_LT', label: 'Geo Distance Lt', description: 'Operador Geo Distance Lt', requiresValue: true, category: 'Geolocalização' },
  { value: 'GEO_DISTANCE_GT', label: 'Geo Distance Gt', description: 'Operador Geo Distance Gt', requiresValue: true, category: 'Geolocalização' },
  { value: 'GEO_IN_POLYGON', label: 'Geo In Polygon', description: 'Operador Geo In Polygon', requiresValue: true, category: 'Geolocalização' },
  { value: 'VELOCITY_COUNT_GT', label: 'Velocity Count Gt', description: 'Operador Velocity Count Gt', requiresValue: true, category: 'Velocity' },
  { value: 'VELOCITY_COUNT_LT', label: 'Velocity Count Lt', description: 'Operador Velocity Count Lt', requiresValue: true, category: 'Velocity' },
  { value: 'VELOCITY_SUM_GT', label: 'Velocity Sum Gt', description: 'Operador Velocity Sum Gt', requiresValue: true, category: 'Velocity' },
  { value: 'VELOCITY_SUM_LT', label: 'Velocity Sum Lt', description: 'Operador Velocity Sum Lt', requiresValue: true, category: 'Velocity' },
  { value: 'VELOCITY_AVG_GT', label: 'Velocity Avg Gt', description: 'Operador Velocity Avg Gt', requiresValue: true, category: 'Velocity' },
  { value: 'VELOCITY_AVG_LT', label: 'Velocity Avg Lt', description: 'Operador Velocity Avg Lt', requiresValue: true, category: 'Velocity' },
  { value: 'VELOCITY_DISTINCT_GT', label: 'Velocity Distinct Gt', description: 'Operador Velocity Distinct Gt', requiresValue: true, category: 'Velocity' },
  { value: 'VELOCITY_DISTINCT_LT', label: 'Velocity Distinct Lt', description: 'Operador Velocity Distinct Lt', requiresValue: true, category: 'Velocity' },
  { value: 'SUM_LAST_N_DAYS', label: 'Sum Last N Days', description: 'Operador Sum Last N Days', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'COUNT_LAST_N_HOURS', label: 'Count Last N Hours', description: 'Operador Count Last N Hours', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'AVG_LAST_N_DAYS', label: 'Avg Last N Days', description: 'Operador Avg Last N Days', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'COUNT_DISTINCT_MERCHANTS_LAST_N_DAYS', label: 'Count Distinct Merchants Last N Days', description: 'Operador Count Distinct Merchants Last N Days', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'COUNT_DISTINCT_COUNTRIES_LAST_N_HOURS', label: 'Count Distinct Countries Last N Hours', description: 'Operador Count Distinct Countries Last N Hours', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'MAX_AMOUNT_LAST_N_DAYS', label: 'Max Amount Last N Days', description: 'Operador Max Amount Last N Days', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'MIN_AMOUNT_LAST_N_DAYS', label: 'Min Amount Last N Days', description: 'Operador Min Amount Last N Days', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'GT_FIELD_MULTIPLIER', label: 'Gt Field Multiplier', description: 'Operador Gt Field Multiplier', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'DECIMAL_PLACES_GT', label: 'Decimal Places Gt', description: 'Operador Decimal Places Gt', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'EXPIRES_WITHIN_DAYS', label: 'Expires Within Days', description: 'Operador Expires Within Days', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'IS_NEW', label: 'Is New', description: 'Operador Is New', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'IS_FIRST', label: 'Is First', description: 'Operador Is First', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'LT_CURRENT_DATE', label: 'Lt Current Date', description: 'Operador Lt Current Date', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'GT_CURRENT_DATE', label: 'Gt Current Date', description: 'Operador Gt Current Date', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'NOT_IN_CUSTOMER_HISTORY', label: 'Not In Customer History', description: 'Operador Not In Customer History', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'IN_CUSTOMER_HISTORY', label: 'In Customer History', description: 'Operador In Customer History', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'NOT_IN_CUSTOMER_USUAL_HOURS', label: 'Not In Customer Usual Hours', description: 'Operador Not In Customer Usual Hours', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'IN_CUSTOMER_USUAL_HOURS', label: 'In Customer Usual Hours', description: 'Operador In Customer Usual Hours', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'IN_CUSTOMER_CHARGEBACK_MERCHANTS', label: 'In Customer Chargeback Merchants', description: 'Operador In Customer Chargeback Merchants', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'PERCENTAGE_OF_FIELD', label: 'Percentage Of Field', description: 'Operador Percentage Of Field', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'HOUR_BETWEEN', label: 'Hour Between', description: 'Operador Hour Between', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'DAY_OF_WEEK_IN', label: 'Day Of Week In', description: 'Operador Day Of Week In', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'IS_WEEKEND', label: 'Is Weekend', description: 'Operador Is Weekend', requiresValue: false, category: 'Agregações Temporais' },
  { value: 'IS_HOLIDAY', label: 'Is Holiday', description: 'Operador Is Holiday', requiresValue: false, category: 'Agregações Temporais' },
  { value: 'DISTANCE_FROM_LAST_GT', label: 'Distance From Last Gt', description: 'Operador Distance From Last Gt', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'TIME_SINCE_LAST_LT', label: 'Time Since Last Lt', description: 'Operador Time Since Last Lt', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'COUNT_FAILURES_LAST_N_HOURS', label: 'Count Failures Last N Hours', description: 'Operador Count Failures Last N Hours', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'SUM_LAST_N_HOURS', label: 'Sum Last N Hours', description: 'Operador Sum Last N Hours', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'COUNT_DISTINCT_MERCHANTS_LAST_N_HOURS', label: 'Count Distinct Merchants Last N Hours', description: 'Operador Count Distinct Merchants Last N Hours', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'VELOCITY_SPIKE', label: 'Velocity Spike', description: 'Operador Velocity Spike', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'AMOUNT_SPIKE', label: 'Amount Spike', description: 'Operador Amount Spike', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'PATTERN_ESCALATION', label: 'Pattern Escalation', description: 'Operador Pattern Escalation', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'PATTERN_ROUND_NUMBERS', label: 'Pattern Round Numbers', description: 'Operador Pattern Round Numbers', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'PATTERN_SPLIT_TRANSACTION', label: 'Pattern Split Transaction', description: 'Operador Pattern Split Transaction', requiresValue: true, category: 'Agregações Temporais' },
  { value: 'NOT_IN_HISTORICAL', label: 'Not In Historical', description: 'Operador Not In Historical', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'NAME_SIMILARITY_LT', label: 'Name Similarity Lt', description: 'Operador Name Similarity Lt', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'GTE_PERCENT_OF_LAST_INCOMING', label: 'Gte Percent Of Last Incoming', description: 'Operador Gte Percent Of Last Incoming', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'DOMAIN_IN_LIST', label: 'Domain In List', description: 'Operador Domain In List', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'CHARGEBACK_RATE_GT', label: 'Chargeback Rate Gt', description: 'Operador Chargeback Rate Gt', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'ACCOUNT_AGE_LT_MINUTES', label: 'Account Age Lt Minutes', description: 'Operador Account Age Lt Minutes', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'IS_VOIP', label: 'Is Voip', description: 'Operador Is Voip', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'COUNT_DISTINCT_PANS_LAST_N_HOURS', label: 'Count Distinct Pans Last N Hours', description: 'Operador Count Distinct Pans Last N Hours', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'COUNT_DISTINCT_ACCOUNTS', label: 'Count Distinct Accounts', description: 'Operador Count Distinct Accounts', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'IN_LIST', label: 'In List', description: 'Operador In List', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'HAS_FAILED_', label: 'Has Failed ', description: 'Operador Has Failed ', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'COUNT_MFA_ABANDONMENTS', label: 'Count Mfa Abandonments', description: 'Operador Count Mfa Abandonments', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'HAS_INCOMING_TRANSFER_LAST_N_HOURS', label: 'Has Incoming Transfer Last N Hours', description: 'Operador Has Incoming Transfer Last N Hours', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'IS_IMPOSSIBLE_COMBINATION', label: 'Is Impossible Combination', description: 'Operador Is Impossible Combination', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'PIX_KEY_CHANGED_LAST_N_DAYS', label: 'Pix Key Changed Last N Days', description: 'Operador Pix Key Changed Last N Days', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'CONTAINS_SUSPICIOUS_KEYWORDS', label: 'Contains Suspicious Keywords', description: 'Operador Contains Suspicious Keywords', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'COUNT_CRYPTO_TXN_LAST_N_DAYS', label: 'Count Crypto Txn Last N Days', description: 'Operador Count Crypto Txn Last N Days', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'COUNT_DISTINCT_INSTRUMENTS_LAST_N_DAYS', label: 'Count Distinct Instruments Last N Days', description: 'Operador Count Distinct Instruments Last N Days', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'COUNT_DISTINCT_PAYERS_LAST_N_DAYS', label: 'Count Distinct Payers Last N Days', description: 'Operador Count Distinct Payers Last N Days', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'COUNT_DISTINCT_USER_AGENTS_LAST_N_HOURS', label: 'Count Distinct User Agents Last N Hours', description: 'Operador Count Distinct User Agents Last N Hours', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'COUNT_LAST_N_DAYS', label: 'Count Last N Days', description: 'Operador Count Last N Days', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'COUNT_MFA_DENIALS_LAST_N_HOURS', label: 'Count Mfa Denials Last N Hours', description: 'Operador Count Mfa Denials Last N Hours', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'DAYS_SINCE_LAST_ACTIVITY', label: 'Days Since Last Activity', description: 'Operador Days Since Last Activity', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'DEVICE_CHANGED_IN_SESSION', label: 'Device Changed In Session', description: 'Operador Device Changed In Session', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'IS_CRYPTO_RANSOM_AMOUNT', label: 'Is Crypto Ransom Amount', description: 'Operador Is Crypto Ransom Amount', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'OUTFLOW_RATE_LAST_N_DAYS', label: 'Outflow Rate Last N Days', description: 'Operador Outflow Rate Last N Days', requiresValue: true, category: 'Fraude Avançada' },
  { value: 'VELOCITY_CROSS_CHANNEL', label: 'Velocity Cross Channel', description: 'Operador Velocity Cross Channel', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'VELOCITY_ROLLING_WINDOW', label: 'Velocity Rolling Window', description: 'Operador Velocity Rolling Window', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'VELOCITY_PERCENTILE', label: 'Velocity Percentile', description: 'Operador Velocity Percentile', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'VELOCITY_RATIO_GT', label: 'Velocity Ratio Gt', description: 'Operador Velocity Ratio Gt', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'VELOCITY_TREND', label: 'Velocity Trend', description: 'Operador Velocity Trend', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'COUNT_UNIQUE_BENEFICIARIES_LAST_N_DAYS', label: 'Count Unique Beneficiaries Last N Days', description: 'Operador Count Unique Beneficiaries Last N Days', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'COUNT_UNIQUE_IPS_LAST_N_HOURS', label: 'Count Unique Ips Last N Hours', description: 'Operador Count Unique Ips Last N Hours', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'SUM_BY_CHANNEL_LAST_N_DAYS', label: 'Sum By Channel Last N Days', description: 'Operador Sum By Channel Last N Days', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'AVG_INTERVAL_BETWEEN_TXN', label: 'Avg Interval Between Txn', description: 'Operador Avg Interval Between Txn', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'VELOCITY_ACCELERATION', label: 'Velocity Acceleration', description: 'Operador Velocity Acceleration', requiresValue: true, category: 'Velocity Avançado' },
  { value: 'DORMANCY_REVIVAL', label: 'Dormancy Revival', description: 'Operador Dormancy Revival', requiresValue: true, category: 'Behavioral' },
  { value: 'AMOUNT_DEVIATION_FROM_AVG', label: 'Amount Deviation From Avg', description: 'Operador Amount Deviation From Avg', requiresValue: true, category: 'Behavioral' },
  { value: 'TIME_DEVIATION_FROM_USUAL', label: 'Time Deviation From Usual', description: 'Operador Time Deviation From Usual', requiresValue: true, category: 'Behavioral' },
  { value: 'MERCHANT_DEVIATION', label: 'Merchant Deviation', description: 'Operador Merchant Deviation', requiresValue: true, category: 'Behavioral' },
  { value: 'MICRO_TRANSACTION_TEST', label: 'Micro Transaction Test', description: 'Operador Micro Transaction Test', requiresValue: true, category: 'Behavioral' },
  { value: 'LOCATION_DEVIATION', label: 'Location Deviation', description: 'Operador Location Deviation', requiresValue: true, category: 'Behavioral' },
  { value: 'CHANNEL_SWITCH_PATTERN', label: 'Channel Switch Pattern', description: 'Operador Channel Switch Pattern', requiresValue: true, category: 'Behavioral' },
  { value: 'BENEFICIARY_REUSE_PATTERN', label: 'Beneficiary Reuse Pattern', description: 'Operador Beneficiary Reuse Pattern', requiresValue: true, category: 'Behavioral' },
  { value: 'FAN_OUT_COUNT', label: 'Fan Out Count', description: 'Operador Fan Out Count', requiresValue: true, category: 'Graph/Network' },
  { value: 'FAN_IN_COUNT', label: 'Fan In Count', description: 'Operador Fan In Count', requiresValue: true, category: 'Graph/Network' },
  { value: 'SHARED_DEVICE_COUNT', label: 'Shared Device Count', description: 'Operador Shared Device Count', requiresValue: true, category: 'Graph/Network' },
  { value: 'SHARED_IP_COUNT', label: 'Shared Ip Count', description: 'Operador Shared Ip Count', requiresValue: true, category: 'Graph/Network' },
  { value: 'ACCOUNT_LINK_DEPTH', label: 'Account Link Depth', description: 'Operador Account Link Depth', requiresValue: true, category: 'Graph/Network' },
  { value: 'CIRCULAR_TRANSFER_DETECTION', label: 'Circular Transfer Detection', description: 'Operador Circular Transfer Detection', requiresValue: true, category: 'Graph/Network' },
  { value: 'RAPID_MULTI_HOP', label: 'Rapid Multi Hop', description: 'Operador Rapid Multi Hop', requiresValue: true, category: 'Graph/Network' },
  { value: 'BENEFICIARY_CONCENTRATION', label: 'Beneficiary Concentration', description: 'Operador Beneficiary Concentration', requiresValue: true, category: 'Graph/Network' },
  // Neo4j Graph Operators (18)
  { value: 'NEO4J_WEAKLY_CONNECTED_COMPONENTS', label: 'Neo4j WCC', description: 'Componentes fracamente conectados (WCC) - detecta clusters de contas relacionadas', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_DEGREE_CENTRALITY', label: 'Neo4j Degree Centrality', description: 'Centralidade de grau - identifica nós com muitas conexões', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_PAGERANK_FRAUD_SCORE', label: 'Neo4j PageRank Fraud', description: 'Score de fraude via PageRank - identifica nós influentes na rede', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_LOUVAIN_COMMUNITY_DETECTION', label: 'Neo4j Louvain Community', description: 'Detecção de comunidade Louvain - agrupa contas em comunidades', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_PAIRWISE_SIMILARITY_PII', label: 'Neo4j Pairwise Similarity', description: 'Similaridade de PII entre pares de entidades', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_ENTITY_RESOLUTION_SHARED_PII', label: 'Neo4j Entity Resolution', description: 'Resolução de entidade por PII compartilhado', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_FRAUD_RING_DETECTION', label: 'Neo4j Fraud Ring', description: 'Detecção de anel de fraude - identifica grupos coordenados', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_MONEY_MULE_NETWORK_ANALYSIS', label: 'Neo4j Money Mule Network', description: 'Análise de rede de money mules', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_CIRCULAR_TRANSACTION_DETECTION', label: 'Neo4j Circular Transaction', description: 'Detecção de transação circular no grafo', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_FIRST_PARTY_FRAUD_CLUSTERING', label: 'Neo4j First Party Fraud', description: 'Clustering de fraude de primeira parte', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_SECOND_LEVEL_FRAUDSTER_ID', label: 'Neo4j Second Level Fraudster', description: 'Identificação de fraudador de segundo nível', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_BETWEENNESS_CENTRALITY_MULE', label: 'Neo4j Betweenness Centrality', description: 'Centralidade de intermediação para detectar mules', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_LABEL_PROPAGATION_FRAUD_SPREAD', label: 'Neo4j Label Propagation', description: 'Propagação de label de fraude na rede', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_SHORTEST_PATH_AML_TRACKING', label: 'Neo4j Shortest Path AML', description: 'Rastreamento AML via caminho mais curto', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_TRIANGLE_COUNT_COLLUSION', label: 'Neo4j Triangle Count', description: 'Contagem de triângulos para detectar colusão', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_NODE_SIMILARITY_SYNTHETIC_ID', label: 'Neo4j Node Similarity', description: 'Similaridade de nó para detectar ID sintético', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_GRAPH_EMBEDDING_FRAUD_PREDICTION', label: 'Neo4j Graph Embedding', description: 'Predição de fraude via embedding de grafo', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'NEO4J_TEMPORAL_MOTIF_PATTERN', label: 'Neo4j Temporal Motif', description: 'Padrão de motif temporal no grafo', requiresValue: true, category: 'Neo4j Graph' },
  { value: 'OFAC_LIST_CHECK', label: 'Ofac List Check', description: 'Operador Ofac List Check', requiresValue: true, category: 'Sanctions' },
  { value: 'PEP_LIST_CHECK', label: 'Pep List Check', description: 'Operador Pep List Check', requiresValue: true, category: 'Sanctions' },
  { value: 'ADVERSE_MEDIA_CHECK', label: 'Adverse Media Check', description: 'Operador Adverse Media Check', requiresValue: true, category: 'Sanctions' },
  { value: 'SANCTIONS_COUNTRY_CHECK', label: 'Sanctions Country Check', description: 'Operador Sanctions Country Check', requiresValue: true, category: 'Sanctions' },
  { value: 'HIGH_RISK_JURISDICTION', label: 'High Risk Jurisdiction', description: 'Operador High Risk Jurisdiction', requiresValue: true, category: 'Sanctions' },
  { value: 'NAME_TRANSLITERATION_MATCH', label: 'Name Transliteration Match', description: 'Operador Name Transliteration Match', requiresValue: true, category: 'Sanctions' },
  { value: 'ALIAS_DETECTION', label: 'Alias Detection', description: 'Operador Alias Detection', requiresValue: true, category: 'Sanctions' },
  { value: 'CPF_SSN_VALIDATION', label: 'Cpf Ssn Validation', description: 'Operador Cpf Ssn Validation', requiresValue: true, category: 'Synthetic ID' },
  { value: 'PHONE_CARRIER_CHECK', label: 'Phone Carrier Check', description: 'Operador Phone Carrier Check', requiresValue: true, category: 'Synthetic ID' },
  { value: 'EMAIL_DOMAIN_AGE', label: 'Email Domain Age', description: 'Operador Email Domain Age', requiresValue: true, category: 'Synthetic ID' },
  { value: 'ADDRESS_VERIFICATION', label: 'Address Verification', description: 'Operador Address Verification', requiresValue: true, category: 'Synthetic ID' },
  { value: 'IDENTITY_VELOCITY', label: 'Identity Velocity', description: 'Operador Identity Velocity', requiresValue: true, category: 'Synthetic ID' },
  { value: 'DEVICE_ACCOUNT_RATIO', label: 'Device Account Ratio', description: 'Operador Device Account Ratio', requiresValue: true, category: 'Synthetic ID' },
  { value: 'EMAIL_PHONE_MISMATCH', label: 'Email Phone Mismatch', description: 'Operador Email Phone Mismatch', requiresValue: true, category: 'Synthetic ID' },
  { value: 'CREDIT_FILE_THIN', label: 'Credit File Thin', description: 'Operador Credit File Thin', requiresValue: true, category: 'Synthetic ID' },
  { value: 'STRUCTURING_DETECTION', label: 'Structuring Detection', description: 'Operador Structuring Detection', requiresValue: true, category: 'AML' },
  { value: 'LAYERING_PATTERN', label: 'Layering Pattern', description: 'Operador Layering Pattern', requiresValue: true, category: 'AML' },
  { value: 'RAPID_MOVEMENT', label: 'Rapid Movement', description: 'Operador Rapid Movement', requiresValue: true, category: 'AML' },
  { value: 'INTEGRATION_PATTERN', label: 'Integration Pattern', description: 'Operador Integration Pattern', requiresValue: true, category: 'AML' },
  { value: 'CASH_INTENSIVE_RATIO', label: 'Cash Intensive Ratio', description: 'Operador Cash Intensive Ratio', requiresValue: true, category: 'AML' },
  { value: 'UNUSUAL_BUSINESS_PATTERN', label: 'Unusual Business Pattern', description: 'Operador Unusual Business Pattern', requiresValue: true, category: 'AML' },
  { value: 'SHELL_COMPANY_INDICATOR', label: 'Shell Company Indicator', description: 'Operador Shell Company Indicator', requiresValue: true, category: 'AML' },
  { value: 'TRADE_BASED_ML_INDICATOR', label: 'Trade Based Ml Indicator', description: 'Operador Trade Based Ml Indicator', requiresValue: true, category: 'AML' },
  { value: 'SCA_EXEMPTION_TRA', label: 'Sca Exemption Tra', description: 'Operador Sca Exemption Tra', requiresValue: true, category: 'Regulatory' },
  { value: 'SCA_EXEMPTION_LOW_VALUE', label: 'Sca Exemption Low Value', description: 'Operador Sca Exemption Low Value', requiresValue: true, category: 'Regulatory' },
  { value: 'SCA_EXEMPTION_TRUSTED_BENEFICIARY', label: 'Sca Exemption Trusted Beneficiary', description: 'Operador Sca Exemption Trusted Beneficiary', requiresValue: true, category: 'Regulatory' },
  { value: 'SCA_EXEMPTION_RECURRING', label: 'Sca Exemption Recurring', description: 'Operador Sca Exemption Recurring', requiresValue: true, category: 'Regulatory' },
  { value: 'PSD', label: 'Psd', description: 'Operador Psd', requiresValue: true, category: 'Regulatory' },
  { value: 'DORA_INCIDENT_SEVERITY', label: 'Dora Incident Severity', description: 'Operador Dora Incident Severity', requiresValue: true, category: 'Regulatory' },
  { value: 'EIDAS_ASSURANCE_LEVEL', label: 'Eidas Assurance Level', description: 'Operador Eidas Assurance Level', requiresValue: true, category: 'Regulatory' },
  { value: 'GDPR_DATA_RETENTION_CHECK', label: 'Gdpr Data Retention Check', description: 'Operador Gdpr Data Retention Check', requiresValue: true, category: 'Regulatory' },
  { value: 'DEVICE_JAILBREAK_ROOTED', label: 'Device Jailbreak Rooted', description: 'Operador Device Jailbreak Rooted', requiresValue: true, category: 'Device' },
  { value: 'EMULATOR_DETECTION', label: 'Emulator Detection', description: 'Operador Emulator Detection', requiresValue: true, category: 'Device' },
  { value: 'VPN_PROXY_DETECTION', label: 'Vpn Proxy Detection', description: 'Operador Vpn Proxy Detection', requiresValue: true, category: 'Device' },
  { value: 'TOR_EXIT_NODE', label: 'Tor Exit Node', description: 'Operador Tor Exit Node', requiresValue: true, category: 'Device' },
  { value: 'BROWSER_INCONSISTENCY', label: 'Browser Inconsistency', description: 'Operador Browser Inconsistency', requiresValue: true, category: 'Device' },
  { value: 'TIMEZONE_MISMATCH', label: 'Timezone Mismatch', description: 'Operador Timezone Mismatch', requiresValue: true, category: 'Device' },
  { value: 'LANGUAGE_MISMATCH', label: 'Language Mismatch', description: 'Operador Language Mismatch', requiresValue: true, category: 'Device' },
  { value: 'MCC_HIGH_RISK', label: 'Mcc High Risk', description: 'Operador Mcc High Risk', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'MCC_GAMBLING', label: 'Mcc Gambling', description: 'Operador Mcc Gambling', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'MCC_CRYPTO', label: 'Mcc Crypto', description: 'Operador Mcc Crypto', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'MERCHANT_FIRST_SEEN', label: 'Merchant First Seen', description: 'Operador Merchant First Seen', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'MERCHANT_COUNTRY_MISMATCH', label: 'Merchant Country Mismatch', description: 'Operador Merchant Country Mismatch', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'MERCHANT_CATEGORY_CHANGE', label: 'Merchant Category Change', description: 'Operador Merchant Category Change', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'MERCHANT_VELOCITY_SPIKE', label: 'Merchant Velocity Spike', description: 'Operador Merchant Velocity Spike', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'PACS', label: 'Pacs', description: 'Operador Pacs', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'REMITTANCE_INFO_ANALYSIS', label: 'Remittance Info Analysis', description: 'Operador Remittance Info Analysis', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'PURPOSE_CODE_MISMATCH', label: 'Purpose Code Mismatch', description: 'Operador Purpose Code Mismatch', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'UETR_DUPLICATE_CHECK', label: 'Uetr Duplicate Check', description: 'Operador Uetr Duplicate Check', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'CREDITOR_NAME_VALIDATION', label: 'Creditor Name Validation', description: 'Operador Creditor Name Validation', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'STRUCTURED_ADDRESS_CHECK', label: 'Structured Address Check', description: 'Operador Structured Address Check', requiresValue: true, category: 'Merchant/MCC' },
  { value: 'BENFORD_LAW_DEVIATION', label: 'Benford Law Deviation', description: 'Operador Benford Law Deviation', requiresValue: true, category: 'Estatísticos' },
  { value: 'Z_SCORE_GT', label: 'Z Score Gt', description: 'Operador Z Score Gt', requiresValue: true, category: 'Estatísticos' },
  { value: 'STANDARD_DEVIATION_GT', label: 'Standard Deviation Gt', description: 'Operador Standard Deviation Gt', requiresValue: true, category: 'Estatísticos' },
  { value: 'PERCENTILE_GT', label: 'Percentile Gt', description: 'Operador Percentile Gt', requiresValue: true, category: 'Estatísticos' },
  { value: 'COEFFICIENT_VARIATION_GT', label: 'Coefficient Variation Gt', description: 'Operador Coefficient Variation Gt', requiresValue: true, category: 'Estatísticos' },
  { value: 'TRANSACTION_COUNT_PER_CARD_HOUR', label: 'Transaction Count Per Card Hour', description: 'Operador Transaction Count Per Card Hour', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'TRANSACTION_COUNT_PER_IP_HOUR', label: 'Transaction Count Per Ip Hour', description: 'Operador Transaction Count Per Ip Hour', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'TRANSACTION_COUNT_PER_DEVICE_DAY', label: 'Transaction Count Per Device Day', description: 'Operador Transaction Count Per Device Day', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'TRANSACTION_COUNT_PER_MERCHANT_HOUR', label: 'Transaction Count Per Merchant Hour', description: 'Operador Transaction Count Per Merchant Hour', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'TRANSACTION_COUNT_PER_CUSTOMER_HOUR', label: 'Transaction Count Per Customer Hour', description: 'Operador Transaction Count Per Customer Hour', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'UNIQUE_CARD_COUNT_PER_IP_HOUR', label: 'Unique Card Count Per Ip Hour', description: 'Operador Unique Card Count Per Ip Hour', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'UNIQUE_MERCHANT_COUNT_PER_CARD_DAY', label: 'Unique Merchant Count Per Card Day', description: 'Operador Unique Merchant Count Per Card Day', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'TRANSACTION_ATTEMPT_COUNT_PER_CARD', label: 'Transaction Attempt Count Per Card', description: 'Operador Transaction Attempt Count Per Card', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'CVV_FAILURE_VELOCITY', label: 'Cvv Failure Velocity', description: 'Operador Cvv Failure Velocity', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'ADDRESS_CHANGE_VELOCITY', label: 'Address Change Velocity', description: 'Operador Address Change Velocity', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'BENEFICIARY_ADD_VELOCITY', label: 'Beneficiary Add Velocity', description: 'Operador Beneficiary Add Velocity', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'CARD_ADD_VELOCITY', label: 'Card Add Velocity', description: 'Operador Card Add Velocity', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'AMOUNT_SUM_PER_CARD_HOUR', label: 'Amount Sum Per Card Hour', description: 'Operador Amount Sum Per Card Hour', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'AMOUNT_SUM_PER_CUSTOMER_DAY', label: 'Amount Sum Per Customer Day', description: 'Operador Amount Sum Per Customer Day', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'AVG_TRANSACTION_SPIKE', label: 'Avg Transaction Spike', description: 'Operador Avg Transaction Spike', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'LARGE_AMOUNT_FREQUENCY', label: 'Large Amount Frequency', description: 'Operador Large Amount Frequency', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'SMALL_AMOUNT_VELOCITY', label: 'Small Amount Velocity', description: 'Operador Small Amount Velocity', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'ROUND_AMOUNT_FREQUENCY', label: 'Round Amount Frequency', description: 'Operador Round Amount Frequency', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'SEQUENTIAL_AMOUNT_PATTERN', label: 'Sequential Amount Pattern', description: 'Operador Sequential Amount Pattern', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'AMOUNT_VARIANCE_ANOMALY', label: 'Amount Variance Anomaly', description: 'Operador Amount Variance Anomaly', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'DAILY_LIMIT_PROXIMITY', label: 'Daily Limit Proximity', description: 'Operador Daily Limit Proximity', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'WEEKLY_LIMIT_PROXIMITY', label: 'Weekly Limit Proximity', description: 'Operador Weekly Limit Proximity', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'TIME_BETWEEN_CONSECUTIVE_TX', label: 'Time Between Consecutive Tx', description: 'Operador Time Between Consecutive Tx', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'TRANSACTION_FREQUENCY_ANOMALY', label: 'Transaction Frequency Anomaly', description: 'Operador Transaction Frequency Anomaly', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'TIME_OF_DAY_ANOMALY', label: 'Time Of Day Anomaly', description: 'Operador Time Of Day Anomaly', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'DORMANCY_ALERT_VELOCITY', label: 'Dormancy Alert Velocity', description: 'Operador Dormancy Alert Velocity', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'WEEKEND_VS_WEEKDAY_PATTERN', label: 'Weekend Vs Weekday Pattern', description: 'Operador Weekend Vs Weekday Pattern', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'HOLIDAY_TRANSACTION_SPIKE', label: 'Holiday Transaction Spike', description: 'Operador Holiday Transaction Spike', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'NIGHTTIME_TRANSACTION_RATIO', label: 'Nighttime Transaction Ratio', description: 'Operador Nighttime Transaction Ratio', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'BUSINESS_HOURS_DEVIATION', label: 'Business Hours Deviation', description: 'Operador Business Hours Deviation', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'DEVICE_TRUST_SCORE', label: 'Device Trust Score', description: 'Operador Device Trust Score', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'CANVAS_FINGERPRINT_MISMATCH', label: 'Canvas Fingerprint Mismatch', description: 'Operador Canvas Fingerprint Mismatch', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'WEBGL_FINGERPRINT_ANOMALY', label: 'Webgl Fingerprint Anomaly', description: 'Operador Webgl Fingerprint Anomaly', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'AUDIO_FINGERPRINT_NEW', label: 'Audio Fingerprint New', description: 'Operador Audio Fingerprint New', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'FONTS_FINGERPRINT_ANOMALY', label: 'Fonts Fingerprint Anomaly', description: 'Operador Fonts Fingerprint Anomaly', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'SCREEN_RESOLUTION_CHANGE', label: 'Screen Resolution Change', description: 'Operador Screen Resolution Change', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'BATTERY_LEVEL_ANOMALY', label: 'Battery Level Anomaly', description: 'Operador Battery Level Anomaly', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'HARDWARE_CONCURRENCY_MISMATCH', label: 'Hardware Concurrency Mismatch', description: 'Operador Hardware Concurrency Mismatch', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'TOUCH_SUPPORT_INCONSISTENCY', label: 'Touch Support Inconsistency', description: 'Operador Touch Support Inconsistency', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'DEVICE_MEMORY_ANOMALY', label: 'Device Memory Anomaly', description: 'Operador Device Memory Anomaly', requiresValue: true, category: 'Velocity Phase 1' },
  { value: 'BEHAVIORAL_BASELINE_DEVIATION', label: 'Behavioral Baseline Deviation', description: 'Operador Behavioral Baseline Deviation', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SPENDING_CATEGORY_SHIFT', label: 'Spending Category Shift', description: 'Operador Spending Category Shift', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'TRANSACTION_SIZE_ESCALATION', label: 'Transaction Size Escalation', description: 'Operador Transaction Size Escalation', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FREQUENCY_PATTERN_CHANGE', label: 'Frequency Pattern Change', description: 'Operador Frequency Pattern Change', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'TIME_PREFERENCE_SHIFT', label: 'Time Preference Shift', description: 'Operador Time Preference Shift', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'CHANNEL_USAGE_ANOMALY', label: 'Channel Usage Anomaly', description: 'Operador Channel Usage Anomaly', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PAYMENT_METHOD_SWITCH', label: 'Payment Method Switch', description: 'Operador Payment Method Switch', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'RECIPIENT_DIVERSITY_CHANGE', label: 'Recipient Diversity Change', description: 'Operador Recipient Diversity Change', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'GEOGRAPHIC_BEHAVIOR_SHIFT', label: 'Geographic Behavior Shift', description: 'Operador Geographic Behavior Shift', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SESSION_BEHAVIOR_ANOMALY', label: 'Session Behavior Anomaly', description: 'Operador Session Behavior Anomaly', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LOGIN_PATTERN_DEVIATION', label: 'Login Pattern Deviation', description: 'Operador Login Pattern Deviation', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NAVIGATION_PATTERN_ANOMALY', label: 'Navigation Pattern Anomaly', description: 'Operador Navigation Pattern Anomaly', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'TRANSACTION_TIMING_CLUSTER', label: 'Transaction Timing Cluster', description: 'Operador Transaction Timing Cluster', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'AMOUNT_ROUNDING_BEHAVIOR', label: 'Amount Rounding Behavior', description: 'Operador Amount Rounding Behavior', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SPLIT_PAYMENT_PATTERN', label: 'Split Payment Pattern', description: 'Operador Split Payment Pattern', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'CHI_SQUARE_DISTRIBUTION_TEST', label: 'Chi Square Distribution Test', description: 'Operador Chi Square Distribution Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'KOLMOGOROV_SMIRNOV_TEST', label: 'Kolmogorov Smirnov Test', description: 'Operador Kolmogorov Smirnov Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ANDERSON_DARLING_TEST', label: 'Anderson Darling Test', description: 'Operador Anderson Darling Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'T_TEST_AMOUNT_DEVIATION', label: 'T Test Amount Deviation', description: 'Operador T Test Amount Deviation', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MANN_WHITNEY_U_TEST', label: 'Mann Whitney U Test', description: 'Operador Mann Whitney U Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'CORRELATION_ANOMALY', label: 'Correlation Anomaly', description: 'Operador Correlation Anomaly', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'REGRESSION_RESIDUAL_OUTLIER', label: 'Regression Residual Outlier', description: 'Operador Regression Residual Outlier', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'VARIANCE_RATIO_TEST', label: 'Variance Ratio Test', description: 'Operador Variance Ratio Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ENTROPY_SCORE_ANOMALY', label: 'Entropy Score Anomaly', description: 'Operador Entropy Score Anomaly', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SKEWNESS_KURTOSIS_ANOMALY', label: 'Skewness Kurtosis Anomaly', description: 'Operador Skewness Kurtosis Anomaly', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MCC_CATEGORY_VELOCITY', label: 'Mcc Category Velocity', description: 'Operador Mcc Category Velocity', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MCC_SPENDING_LIMIT_CHECK', label: 'Mcc Spending Limit Check', description: 'Operador Mcc Spending Limit Check', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MCC_CROSS_CATEGORY_PATTERN', label: 'Mcc Cross Category Pattern', description: 'Operador Mcc Cross Category Pattern', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_REPUTATION_SCORE', label: 'Merchant Reputation Score', description: 'Operador Merchant Reputation Score', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_AGE_CHECK', label: 'Merchant Age Check', description: 'Operador Merchant Age Check', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_TRANSACTION_VOLUME', label: 'Merchant Transaction Volume', description: 'Operador Merchant Transaction Volume', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_CHARGEBACK_HISTORY', label: 'Merchant Chargeback History', description: 'Operador Merchant Chargeback History', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_FRAUD_RATE_CHECK', label: 'Merchant Fraud Rate Check', description: 'Operador Merchant Fraud Rate Check', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_GEOGRAPHIC_SPREAD', label: 'Merchant Geographic Spread', description: 'Operador Merchant Geographic Spread', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_CUSTOMER_CONCENTRATION', label: 'Merchant Customer Concentration', description: 'Operador Merchant Customer Concentration', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_AMOUNT_DISTRIBUTION', label: 'Merchant Amount Distribution', description: 'Operador Merchant Amount Distribution', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_TIME_PATTERN', label: 'Merchant Time Pattern', description: 'Operador Merchant Time Pattern', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_DEVICE_DIVERSITY', label: 'Merchant Device Diversity', description: 'Operador Merchant Device Diversity', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_REFUND_RATIO', label: 'Merchant Refund Ratio', description: 'Operador Merchant Refund Ratio', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_NEW_CUSTOMER_RATIO', label: 'Merchant New Customer Ratio', description: 'Operador Merchant New Customer Ratio', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_DORMANT_REACTIVATION', label: 'Merchant Dormant Reactivation', description: 'Operador Merchant Dormant Reactivation', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_CROSS_BORDER_RATIO', label: 'Merchant Cross Border Ratio', description: 'Operador Merchant Cross Border Ratio', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MERCHANT_HIGH_VALUE_FREQUENCY', label: 'Merchant High Value Frequency', description: 'Operador Merchant High Value Frequency', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_PLACEMENT_CASH_INTENSIVE', label: 'Fatf Placement Cash Intensive', description: 'Operador Fatf Placement Cash Intensive', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_PLACEMENT_STRUCTURING', label: 'Fatf Placement Structuring', description: 'Operador Fatf Placement Structuring', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_PLACEMENT_SMURFING', label: 'Fatf Placement Smurfing', description: 'Operador Fatf Placement Smurfing', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_PLACEMENT_CURRENCY_EXCHANGE', label: 'Fatf Placement Currency Exchange', description: 'Operador Fatf Placement Currency Exchange', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_PLACEMENT_CASINO_GAMBLING', label: 'Fatf Placement Casino Gambling', description: 'Operador Fatf Placement Casino Gambling', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_LAYERING_RAPID_MOVEMENT', label: 'Fatf Layering Rapid Movement', description: 'Operador Fatf Layering Rapid Movement', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_LAYERING_SHELL_COMPANY', label: 'Fatf Layering Shell Company', description: 'Operador Fatf Layering Shell Company', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_LAYERING_OFFSHORE', label: 'Fatf Layering Offshore', description: 'Operador Fatf Layering Offshore', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_LAYERING_WIRE_CHAINS', label: 'Fatf Layering Wire Chains', description: 'Operador Fatf Layering Wire Chains', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_LAYERING_CONVERTIBLE_INSTRUMENTS', label: 'Fatf Layering Convertible Instruments', description: 'Operador Fatf Layering Convertible Instruments', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_INTEGRATION_REAL_ESTATE', label: 'Fatf Integration Real Estate', description: 'Operador Fatf Integration Real Estate', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_INTEGRATION_LUXURY_GOODS', label: 'Fatf Integration Luxury Goods', description: 'Operador Fatf Integration Luxury Goods', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_INTEGRATION_BUSINESS_INVESTMENT', label: 'Fatf Integration Business Investment', description: 'Operador Fatf Integration Business Investment', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_INTEGRATION_LOAN_REPAYMENT', label: 'Fatf Integration Loan Repayment', description: 'Operador Fatf Integration Loan Repayment', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_TBML_OVER_INVOICING', label: 'Fatf Tbml Over Invoicing', description: 'Operador Fatf Tbml Over Invoicing', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_TBML_UNDER_INVOICING', label: 'Fatf Tbml Under Invoicing', description: 'Operador Fatf Tbml Under Invoicing', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_TBML_PHANTOM_SHIPPING', label: 'Fatf Tbml Phantom Shipping', description: 'Operador Fatf Tbml Phantom Shipping', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_TBML_MULTIPLE_INVOICING', label: 'Fatf Tbml Multiple Invoicing', description: 'Operador Fatf Tbml Multiple Invoicing', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_TBML_FALSE_DESCRIPTION', label: 'Fatf Tbml False Description', description: 'Operador Fatf Tbml False Description', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_HAWALA_INFORMAL', label: 'Fatf Hawala Informal', description: 'Operador Fatf Hawala Informal', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_NEW_PAYMENT_EXPLOITATION', label: 'Fatf New Payment Exploitation', description: 'Operador Fatf New Payment Exploitation', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_CRYPTO_MIXING', label: 'Fatf Crypto Mixing', description: 'Operador Fatf Crypto Mixing', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_CRYPTO_ATM_CASHOUT', label: 'Fatf Crypto Atm Cashout', description: 'Operador Fatf Crypto Atm Cashout', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_PEP_TRANSACTION', label: 'Fatf Pep Transaction', description: 'Operador Fatf Pep Transaction', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_CORRESPONDENT_LAYERING', label: 'Fatf Correspondent Layering', description: 'Operador Fatf Correspondent Layering', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_ROUND_TRIPPING', label: 'Fatf Round Tripping', description: 'Operador Fatf Round Tripping', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_BLACK_MARKET_EXCHANGE', label: 'Fatf Black Market Exchange', description: 'Operador Fatf Black Market Exchange', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FATF_INSURANCE_CASH_VALUE', label: 'Fatf Insurance Cash Value', description: 'Operador Fatf Insurance Cash Value', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_LOW_VALUE_EXEMPTION', label: 'Sca Low Value Exemption', description: 'Operador Sca Low Value Exemption', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_CONTACTLESS_EXEMPTION', label: 'Sca Contactless Exemption', description: 'Operador Sca Contactless Exemption', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_TRA_EXEMPTION', label: 'Sca Tra Exemption', description: 'Operador Sca Tra Exemption', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_TRUSTED_BENEFICIARY', label: 'Sca Trusted Beneficiary', description: 'Operador Sca Trusted Beneficiary', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_RECURRING_TRANSACTION', label: 'Sca Recurring Transaction', description: 'Operador Sca Recurring Transaction', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_MERCHANT_INITIATED', label: 'Sca Merchant Initiated', description: 'Operador Sca Merchant Initiated', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_CORPORATE_PAYMENT', label: 'Sca Corporate Payment', description: 'Operador Sca Corporate Payment', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_SECURE_CORPORATE_PROTOCOL', label: 'Sca Secure Corporate Protocol', description: 'Operador Sca Secure Corporate Protocol', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_LIABILITY_SHIFT', label: 'Sca Liability Shift', description: 'Operador Sca Liability Shift', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_DYNAMIC_', label: 'Sca Dynamic ', description: 'Operador Sca Dynamic ', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_FRAUD_RATE_MONITORING', label: 'Sca Fraud Rate Monitoring', description: 'Operador Sca Fraud Rate Monitoring', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SCA_CHALLENGE_MANDATORY', label: 'Sca Challenge Mandatory', description: 'Operador Sca Challenge Mandatory', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_BEHAVIOR_SORTED_LISTS', label: 'Plt Behavior Sorted Lists', description: 'Operador Plt Behavior Sorted Lists', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_BUSINESS_RULES_SCENARIO', label: 'Plt Business Rules Scenario', description: 'Operador Plt Business Rules Scenario', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_IDENTITY_RESOLUTION', label: 'Plt Identity Resolution', description: 'Operador Plt Identity Resolution', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_COMPROMISE_MANAGER', label: 'Plt Compromise Manager', description: 'Operador Plt Compromise Manager', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_INTELLIGENCE_NETWORK', label: 'Plt Intelligence Network', description: 'Operador Plt Intelligence Network', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_RULES_MODELS_HYBRID', label: 'Plt Rules Models Hybrid', description: 'Operador Plt Rules Models Hybrid', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_BEHAVIORAL_PROFILING', label: 'Plt Behavioral Profiling', description: 'Operador Plt Behavioral Profiling', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_NETWORK_ANALYTICS', label: 'Plt Network Analytics', description: 'Operador Plt Network Analytics', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_SAR_AUTOMATED', label: 'Plt Sar Automated', description: 'Operador Plt Sar Automated', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_DS', label: 'Plt Ds', description: 'Operador Plt Ds', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_REAL_TIME_DETECTION', label: 'Plt Real Time Detection', description: 'Operador Plt Real Time Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_NETWORK_ENTITY_RESOLUTION', label: 'Plt Network Entity Resolution', description: 'Operador Plt Network Entity Resolution', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_SCENARIO_SCORECARD', label: 'Plt Scenario Scorecard', description: 'Operador Plt Scenario Scorecard', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_RADAR_RULE_BACKTESTING', label: 'Plt Radar Rule Backtesting', description: 'Operador Plt Radar Rule Backtesting', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_RADAR_METADATA_MATCHING', label: 'Plt Radar Metadata Matching', description: 'Operador Plt Radar Metadata Matching', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_RADAR_INLINE_LISTS', label: 'Plt Radar Inline Lists', description: 'Operador Plt Radar Inline Lists', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_RADAR_COMPLEX_CONDITIONS', label: 'Plt Radar Complex Conditions', description: 'Operador Plt Radar Complex Conditions', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_RISK_PROFILE_ASSIGNMENT', label: 'Plt Risk Profile Assignment', description: 'Operador Plt Risk Profile Assignment', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_CUSTOM_RULE_BUILDER', label: 'Plt Custom Rule Builder', description: 'Operador Plt Custom Rule Builder', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_RISK_LIST_COMPARISON', label: 'Plt Risk List Comparison', description: 'Operador Plt Risk List Comparison', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_BACKTESTING_LABELING', label: 'Plt Backtesting Labeling', description: 'Operador Plt Backtesting Labeling', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_ML_FRAUD_RISK_OUTCOME', label: 'Plt Ml Fraud Risk Outcome', description: 'Operador Plt Ml Fraud Risk Outcome', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_RISK_SCORE_CALCULATION', label: 'Plt Risk Score Calculation', description: 'Operador Plt Risk Score Calculation', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_VELOCITY_FILTERS', label: 'Plt Velocity Filters', description: 'Operador Plt Velocity Filters', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_LINKING_VELOCITY', label: 'Plt Linking Velocity', description: 'Operador Plt Linking Velocity', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_BAD_ENTITY_NETWORK', label: 'Plt Bad Entity Network', description: 'Operador Plt Bad Entity Network', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_REVIEWLIST_QUEUE', label: 'Plt Reviewlist Queue', description: 'Operador Plt Reviewlist Queue', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PLT_CONSORTIUM_DATA_CHECK', label: 'Plt Consortium Data Check', description: 'Operador Plt Consortium Data Check', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_BUSINESS_INDICATOR', label: 'Bsl Business Indicator', description: 'Operador Bsl Business Indicator', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_BUSINESS_INDICATOR_COMPONENT', label: 'Bsl Business Indicator Component', description: 'Operador Bsl Business Indicator Component', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_INTERNAL_LOSS_MULTIPLIER', label: 'Bsl Internal Loss Multiplier', description: 'Operador Bsl Internal Loss Multiplier', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_LOSS_DATA_COLLECTION', label: 'Bsl Loss Data Collection', description: 'Operador Bsl Loss Data Collection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_LOSS_EXCLUSION_APPROVAL', label: 'Bsl Loss Exclusion Approval', description: 'Operador Bsl Loss Exclusion Approval', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_BUCKET_CLASSIFICATION', label: 'Bsl Bucket Classification', description: 'Operador Bsl Bucket Classification', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_MARGINAL_COEFFICIENT', label: 'Bsl Marginal Coefficient', description: 'Operador Bsl Marginal Coefficient', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_LOSS_THRESHOLD_SETTING', label: 'Bsl Loss Threshold Setting', description: 'Operador Bsl Loss Threshold Setting', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_RETENTION_PERIOD', label: 'Bsl Retention Period', description: 'Operador Bsl Retention Period', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_RISK_GOVERNANCE', label: 'Bsl Risk Governance', description: 'Operador Bsl Risk Governance', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_LOSS_EVENT_REPORTING', label: 'Bsl Loss Event Reporting', description: 'Operador Bsl Loss Event Reporting', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_CONTROL_DEFICIENCY', label: 'Bsl Control Deficiency', description: 'Operador Bsl Control Deficiency', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_KRI_MONITORING', label: 'Bsl Kri Monitoring', description: 'Operador Bsl Kri Monitoring', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BSL_SCENARIO_ANALYSIS', label: 'Bsl Scenario Analysis', description: 'Operador Bsl Scenario Analysis', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'APRIORI_ASSOCIATION', label: 'Apriori Association', description: 'Operador Apriori Association', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FPGROWTH_FREQUENT_PATTERNS', label: 'Fpgrowth Frequent Patterns', description: 'Operador Fpgrowth Frequent Patterns', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ECLAT_ITEMSET', label: 'Eclat Itemset', description: 'Operador Eclat Itemset', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FUZZY_MEMBERSHIP', label: 'Fuzzy Membership', description: 'Operador Fuzzy Membership', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FUZZY_ADAPTIVE_THRESHOLD', label: 'Fuzzy Adaptive Threshold', description: 'Operador Fuzzy Adaptive Threshold', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_TRANSACTION_DESCRIPTION_ANALYSIS', label: 'Llm Transaction Description Analysis', description: 'Operador Llm Transaction Description Analysis', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_GENERATIVE_RULE_SYNTHESIS', label: 'Llm Generative Rule Synthesis', description: 'Operador Llm Generative Rule Synthesis', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_ANOMALY_EXPLANATION_GENERATION', label: 'Llm Anomaly Explanation Generation', description: 'Operador Llm Anomaly Explanation Generation', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_CHATBOT_FRAUD_DETECTION', label: 'Llm Chatbot Fraud Detection', description: 'Operador Llm Chatbot Fraud Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_DEEPFAKE_VOICE_DETECTION', label: 'Llm Deepfake Voice Detection', description: 'Operador Llm Deepfake Voice Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_SYNTHETIC_IMAGE_DETECTION', label: 'Llm Synthetic Image Detection', description: 'Operador Llm Synthetic Image Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_EMAIL_PHISHING_ANALYSIS', label: 'Llm Email Phishing Analysis', description: 'Operador Llm Email Phishing Analysis', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_SOCIAL_ENGINEERING_CLASSIFICATION', label: 'Llm Social Engineering Classification', description: 'Operador Llm Social Engineering Classification', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_FRAUD_ALERT_PRIORITIZATION', label: 'Llm Fraud Alert Prioritization', description: 'Operador Llm Fraud Alert Prioritization', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_MULTI_MODAL_FRAUD_DETECTION', label: 'Llm Multi Modal Fraud Detection', description: 'Operador Llm Multi Modal Fraud Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_ADVERSARIAL_ATTACK_RESISTANCE', label: 'Llm Adversarial Attack Resistance', description: 'Operador Llm Adversarial Attack Resistance', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LLM_FRAUD_PATTERN_AUTODISCOVERY', label: 'Llm Fraud Pattern Autodiscovery', description: 'Operador Llm Fraud Pattern Autodiscovery', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NEO', label: 'Neo', description: 'Operador Neo', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BIOMETRIC_KEYSTROKE_DYNAMICS', label: 'Biometric Keystroke Dynamics', description: 'Operador Biometric Keystroke Dynamics', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BIOMETRIC_MOUSE_MOVEMENT', label: 'Biometric Mouse Movement', description: 'Operador Biometric Mouse Movement', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BIOMETRIC_SCROLL_VELOCITY', label: 'Biometric Scroll Velocity', description: 'Operador Biometric Scroll Velocity', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'DEVICE_FINGERPRINT_CONSISTENCY_CHECK', label: 'Device Fingerprint Consistency Check', description: 'Operador Device Fingerprint Consistency Check', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ECBSV_SSN_VALIDATION', label: 'Ecbsv Ssn Validation', description: 'Operador Ecbsv Ssn Validation', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SYNTHETIC_FRAUD_SCORE', label: 'Synthetic Fraud Score', description: 'Operador Synthetic Fraud Score', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'INJECTION_ATTACK_DETECTION', label: 'Injection Attack Detection', description: 'Operador Injection Attack Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LIVENESS_DETECTION_FACIAL', label: 'Liveness Detection Facial', description: 'Operador Liveness Detection Facial', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LIVENESS_DETECTION_VOICE', label: 'Liveness Detection Voice', description: 'Operador Liveness Detection Voice', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ANTI_DETECT_BROWSER_DETECTION', label: 'Anti Detect Browser Detection', description: 'Operador Anti Detect Browser Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'DOCUMENT_FORGERY_DETECTION', label: 'Document Forgery Detection', description: 'Operador Document Forgery Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'FACE_TO_ID_PHOTO_MATCHING', label: 'Face To Id Photo Matching', description: 'Operador Face To Id Photo Matching', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ADAPTIVE_BEHAVIORAL_ANALYTICS', label: 'Adaptive Behavioral Analytics', description: 'Operador Adaptive Behavioral Analytics', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SYNTHETIC_ID_LABEL_CORRECTION', label: 'Synthetic Id Label Correction', description: 'Operador Synthetic Id Label Correction', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MULTI_LAYERED_SYNTHETIC_ID_CONTROLS', label: 'Multi Layered Synthetic Id Controls', description: 'Operador Multi Layered Synthetic Id Controls', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_KRUSKAL_WALLIS_TEST', label: 'Stat Kruskal Wallis Test', description: 'Operador Stat Kruskal Wallis Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_ANOVA_F_TEST', label: 'Stat Anova F Test', description: 'Operador Stat Anova F Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_ISOLATION_FOREST_SCORE', label: 'Stat Isolation Forest Score', description: 'Operador Stat Isolation Forest Score', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_LOCAL_OUTLIER_FACTOR', label: 'Stat Local Outlier Factor', description: 'Operador Stat Local Outlier Factor', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_ONE_CLASS_SVM_BOUNDARY', label: 'Stat One Class Svm Boundary', description: 'Operador Stat One Class Svm Boundary', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_KMEANS_CLUSTER_DISTANCE', label: 'Stat Kmeans Cluster Distance', description: 'Operador Stat Kmeans Cluster Distance', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_DBSCAN_NOISE_DETECTION', label: 'Stat Dbscan Noise Detection', description: 'Operador Stat Dbscan Noise Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_GMM_PROBABILITY', label: 'Stat Gmm Probability', description: 'Operador Stat Gmm Probability', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_MAHALANOBIS_DISTANCE', label: 'Stat Mahalanobis Distance', description: 'Operador Stat Mahalanobis Distance', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_GRUBBS_TEST', label: 'Stat Grubbs Test', description: 'Operador Stat Grubbs Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_DIXON_Q_TEST', label: 'Stat Dixon Q Test', description: 'Operador Stat Dixon Q Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_SHAPIRO_WILK_TEST', label: 'Stat Shapiro Wilk Test', description: 'Operador Stat Shapiro Wilk Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_LEVENE_TEST', label: 'Stat Levene Test', description: 'Operador Stat Levene Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_WELCH_T_TEST', label: 'Stat Welch T Test', description: 'Operador Stat Welch T Test', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'STAT_BOOTSTRAP_CONFIDENCE_INTERVAL', label: 'Stat Bootstrap Confidence Interval', description: 'Operador Stat Bootstrap Confidence Interval', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'CARD_TESTING_RING_DETECTION', label: 'Card Testing Ring Detection', description: 'Operador Card Testing Ring Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'BUST_OUT_PATTERN_DETECTION', label: 'Bust Out Pattern Detection', description: 'Operador Bust Out Pattern Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'CIRCULAR_PAYMENT_DETECTION', label: 'Circular Payment Detection', description: 'Operador Circular Payment Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ACCOUNT_TAKEOVER_PATTERN', label: 'Account Takeover Pattern', description: 'Operador Account Takeover Pattern', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SYNTHETIC_IDENTITY_RING', label: 'Synthetic Identity Ring', description: 'Operador Synthetic Identity Ring', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'CROSS_BORDER_VELOCITY', label: 'Cross Border Velocity', description: 'Operador Cross Border Velocity', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'CORRESPONDENT_ANOMALY', label: 'Correspondent Anomaly', description: 'Operador Correspondent Anomaly', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'NESTED_CORRESPONDENT_CHECK', label: 'Nested Correspondent Check', description: 'Operador Nested Correspondent Check', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SHELL_BANK_INDICATOR', label: 'Shell Bank Indicator', description: 'Operador Shell Bank Indicator', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'HIGH_RISK_CORRIDOR_CHECK', label: 'High Risk Corridor Check', description: 'Operador High Risk Corridor Check', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SEGMENT_OF_ONE_PROFILING', label: 'Segment Of One Profiling', description: 'Operador Segment Of One Profiling', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ADAPTIVE_PARAMETRIC_THRESHOLD', label: 'Adaptive Parametric Threshold', description: 'Operador Adaptive Parametric Threshold', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'REAL_TIME_RISK_SCORING', label: 'Real Time Risk Scoring', description: 'Operador Real Time Risk Scoring', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'CONSORTIUM_NEGATIVE_FILE_CHECK', label: 'Consortium Negative File Check', description: 'Operador Consortium Negative File Check', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PEER_GROUP_DEVIATION_SCORE', label: 'Peer Group Deviation Score', description: 'Operador Peer Group Deviation Score', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'MICRO_DEPOSIT_VELOCITY', label: 'Micro Deposit Velocity', description: 'Operador Micro Deposit Velocity', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'RAPID_SUCCESSION_PATTERN', label: 'Rapid Succession Pattern', description: 'Operador Rapid Succession Pattern', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'SPLIT_TRANSACTION_DETECTION', label: 'Split Transaction Detection', description: 'Operador Split Transaction Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ROUND_TRIP_DETECTION', label: 'Round Trip Detection', description: 'Operador Round Trip Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'LAYERED_TRANSFER_PATTERN', label: 'Layered Transfer Pattern', description: 'Operador Layered Transfer Pattern', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'APP_FRAUD_DETECTION', label: 'App Fraud Detection', description: 'Operador App Fraud Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'ROMANCE_SCAM_INDICATOR', label: 'Romance Scam Indicator', description: 'Operador Romance Scam Indicator', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'INVESTMENT_SCAM_PATTERN', label: 'Investment Scam Pattern', description: 'Operador Investment Scam Pattern', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'CRYPTO_PUMP_DUMP_DETECTION', label: 'Crypto Pump Dump Detection', description: 'Operador Crypto Pump Dump Detection', requiresValue: true, category: 'Behavioral Phase 1B' },
  { value: 'PIG_BUTCHERING_INDICATOR', label: 'Pig Butchering Indicator', description: 'Indicador de pig butchering scam', requiresValue: true, category: 'Behavioral Phase 1B' },
];

export const OPERATOR_COUNT = 465;
