package com.rulex.dto.complex;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/** DTO para condições individuais com suporte a operadores avançados. */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ConditionDTO {

  private UUID id;

  @NotBlank(message = "Nome do campo é obrigatório")
  private String fieldName;

  /** Caminho para campos aninhados (ex: "customer.address.city") */
  private String fieldPath;

  @NotNull(message = "Operador é obrigatório")
  private OperatorType operator;

  @NotNull(message = "Tipo do valor é obrigatório")
  private ValueType valueType;

  /** Valor único para comparação */
  private String valueSingle;

  /** Lista de valores para operadores IN, NOT_IN, etc */
  private List<String> valueArray;

  /** Valor mínimo para operadores BETWEEN */
  private String valueMin;

  /** Valor máximo para operadores BETWEEN */
  private String valueMax;

  /** Referência a outro campo para comparação entre campos */
  private String valueFieldRef;

  /** Expressão calculada (ex: "transactionAmount * 1.1") */
  private String valueExpression;

  /** Se a comparação deve ser case-sensitive (para strings) */
  private Boolean caseSensitive;

  /** Inverte o resultado da condição */
  private Boolean negate;

  private Boolean enabled;

  private Integer position;

  private String description;

  /** Mensagem de erro customizada quando a condição falha */
  private String errorMessage;

  /** Operadores de comparação suportados */
  public enum OperatorType {
    EQ("Eq"),
    NEQ("Neq"),
    GT("Gt"),
    GTE("Gte"),
    LT("Lt"),
    LTE("Lte"),
    IN("In"),
    NOT_IN("Not In"),
    CONTAINS("Contains"),
    NOT_CONTAINS("Not Contains"),
    STARTS_WITH("Starts With"),
    ENDS_WITH("Ends With"),
    REGEX("Regex"),
    NOT_REGEX("Not Regex"),
    IS_NULL("Is Null"),
    NOT_NULL("Not Null"),
    IS_TRUE("Is True"),
    IS_FALSE("Is False"),
    BETWEEN("Between"),
    NOT_BETWEEN("Not Between"),
    FIELD_EQ("Field Eq"),
    FIELD_NEQ("Field Neq"),
    FIELD_GT("Field Gt"),
    FIELD_GTE("Field Gte"),
    FIELD_LT("Field Lt"),
    FIELD_LTE("Field Lte"),
    DATE_BEFORE("Date Before"),
    DATE_AFTER("Date After"),
    DATE_BETWEEN("Date Between"),
    TIME_BEFORE("Time Before"),
    TIME_AFTER("Time After"),
    TIME_BETWEEN("Time Between"),
    ARRAY_CONTAINS("Array Contains"),
    ARRAY_NOT_CONTAINS("Array Not Contains"),
    ARRAY_SIZE_EQ("Array Size Eq"),
    ARRAY_SIZE_GT("Array Size Gt"),
    ARRAY_SIZE_LT("Array Size Lt"),
    MOD_EQ("Mod Eq"),
    MOD_NEQ("Mod Neq"),
    GEO_DISTANCE_LT("Geo Distance Lt"),
    GEO_DISTANCE_GT("Geo Distance Gt"),
    GEO_IN_POLYGON("Geo In Polygon"),
    VELOCITY_COUNT_GT("Velocity Count Gt"),
    VELOCITY_COUNT_LT("Velocity Count Lt"),
    VELOCITY_SUM_GT("Velocity Sum Gt"),
    VELOCITY_SUM_LT("Velocity Sum Lt"),
    VELOCITY_AVG_GT("Velocity Avg Gt"),
    VELOCITY_AVG_LT("Velocity Avg Lt"),
    VELOCITY_DISTINCT_GT("Velocity Distinct Gt"),
    VELOCITY_DISTINCT_LT("Velocity Distinct Lt"),
    SUM_LAST_N_DAYS("Sum Last N Days"),
    COUNT_LAST_N_HOURS("Count Last N Hours"),
    AVG_LAST_N_DAYS("Avg Last N Days"),
    COUNT_DISTINCT_MERCHANTS_LAST_N_DAYS("Count Distinct Merchants Last N Days"),
    COUNT_DISTINCT_COUNTRIES_LAST_N_HOURS("Count Distinct Countries Last N Hours"),
    MAX_AMOUNT_LAST_N_DAYS("Max Amount Last N Days"),
    MIN_AMOUNT_LAST_N_DAYS("Min Amount Last N Days"),
    GT_FIELD_MULTIPLIER("Gt Field Multiplier"),
    DECIMAL_PLACES_GT("Decimal Places Gt"),
    EXPIRES_WITHIN_DAYS("Expires Within Days"),
    IS_NEW("Is New"),
    IS_FIRST("Is First"),
    LT_CURRENT_DATE("Lt Current Date"),
    GT_CURRENT_DATE("Gt Current Date"),
    NOT_IN_CUSTOMER_HISTORY("Not In Customer History"),
    IN_CUSTOMER_HISTORY("In Customer History"),
    NOT_IN_CUSTOMER_USUAL_HOURS("Not In Customer Usual Hours"),
    IN_CUSTOMER_USUAL_HOURS("In Customer Usual Hours"),
    IN_CUSTOMER_CHARGEBACK_MERCHANTS("In Customer Chargeback Merchants"),
    PERCENTAGE_OF_FIELD("Percentage Of Field"),
    HOUR_BETWEEN("Hour Between"),
    DAY_OF_WEEK_IN("Day Of Week In"),
    IS_WEEKEND("Is Weekend"),
    IS_HOLIDAY("Is Holiday"),
    DISTANCE_FROM_LAST_GT("Distance From Last Gt"),
    TIME_SINCE_LAST_LT("Time Since Last Lt"),
    COUNT_FAILURES_LAST_N_HOURS("Count Failures Last N Hours"),
    SUM_LAST_N_HOURS("Sum Last N Hours"),
    COUNT_DISTINCT_MERCHANTS_LAST_N_HOURS("Count Distinct Merchants Last N Hours"),
    VELOCITY_SPIKE("Velocity Spike"),
    AMOUNT_SPIKE("Amount Spike"),
    PATTERN_ESCALATION("Pattern Escalation"),
    PATTERN_ROUND_NUMBERS("Pattern Round Numbers"),
    PATTERN_SPLIT_TRANSACTION("Pattern Split Transaction"),
    NOT_IN_HISTORICAL("Not In Historical"),
    NAME_SIMILARITY_LT("Name Similarity Lt"),
    GTE_PERCENT_OF_LAST_INCOMING("Gte Percent Of Last Incoming"),
    DOMAIN_IN_LIST("Domain In List"),
    CHARGEBACK_RATE_GT("Chargeback Rate Gt"),
    ACCOUNT_AGE_LT_MINUTES("Account Age Lt Minutes"),
    IS_VOIP("Is Voip"),
    COUNT_DISTINCT_PANS_LAST_N_HOURS("Count Distinct Pans Last N Hours"),
    COUNT_DISTINCT_ACCOUNTS("Count Distinct Accounts"),
    IN_LIST("In List"),
    HAS_FAILED_3DS_LAST_N_MINUTES("Has Failed 3Ds Last N Minutes"),
    COUNT_MFA_ABANDONMENTS("Count Mfa Abandonments"),
    HAS_INCOMING_TRANSFER_LAST_N_HOURS("Has Incoming Transfer Last N Hours"),
    IS_IMPOSSIBLE_COMBINATION("Is Impossible Combination"),
    PIX_KEY_CHANGED_LAST_N_DAYS("Pix Key Changed Last N Days"),
    CONTAINS_SUSPICIOUS_KEYWORDS("Contains Suspicious Keywords"),
    COUNT_CRYPTO_TXN_LAST_N_DAYS("Count Crypto Txn Last N Days"),
    COUNT_DISTINCT_INSTRUMENTS_LAST_N_DAYS("Count Distinct Instruments Last N Days"),
    COUNT_DISTINCT_PAYERS_LAST_N_DAYS("Count Distinct Payers Last N Days"),
    COUNT_DISTINCT_USER_AGENTS_LAST_N_HOURS("Count Distinct User Agents Last N Hours"),
    COUNT_LAST_N_DAYS("Count Last N Days"),
    COUNT_MFA_DENIALS_LAST_N_HOURS("Count Mfa Denials Last N Hours"),
    DAYS_SINCE_LAST_ACTIVITY("Days Since Last Activity"),
    DEVICE_CHANGED_IN_SESSION("Device Changed In Session"),
    IS_CRYPTO_RANSOM_AMOUNT("Is Crypto Ransom Amount"),
    OUTFLOW_RATE_LAST_N_DAYS("Outflow Rate Last N Days"),
    VELOCITY_CROSS_CHANNEL("Velocity Cross Channel"),
    VELOCITY_ROLLING_WINDOW("Velocity Rolling Window"),
    VELOCITY_PERCENTILE("Velocity Percentile"),
    VELOCITY_RATIO_GT("Velocity Ratio Gt"),
    VELOCITY_TREND("Velocity Trend"),
    COUNT_UNIQUE_BENEFICIARIES_LAST_N_DAYS("Count Unique Beneficiaries Last N Days"),
    COUNT_UNIQUE_IPS_LAST_N_HOURS("Count Unique Ips Last N Hours"),
    SUM_BY_CHANNEL_LAST_N_DAYS("Sum By Channel Last N Days"),
    AVG_INTERVAL_BETWEEN_TXN("Avg Interval Between Txn"),
    VELOCITY_ACCELERATION("Velocity Acceleration"),
    DORMANCY_REVIVAL("Dormancy Revival"),
    AMOUNT_DEVIATION_FROM_AVG("Amount Deviation From Avg"),
    TIME_DEVIATION_FROM_USUAL("Time Deviation From Usual"),
    MERCHANT_DEVIATION("Merchant Deviation"),
    MICRO_TRANSACTION_TEST("Micro Transaction Test"),
    LOCATION_DEVIATION("Location Deviation"),
    CHANNEL_SWITCH_PATTERN("Channel Switch Pattern"),
    BENEFICIARY_REUSE_PATTERN("Beneficiary Reuse Pattern"),
    FAN_OUT_COUNT("Fan Out Count"),
    FAN_IN_COUNT("Fan In Count"),
    SHARED_DEVICE_COUNT("Shared Device Count"),
    SHARED_IP_COUNT("Shared Ip Count"),
    ACCOUNT_LINK_DEPTH("Account Link Depth"),
    CIRCULAR_TRANSFER_DETECTION("Circular Transfer Detection"),
    RAPID_MULTI_HOP("Rapid Multi Hop"),
    BENEFICIARY_CONCENTRATION("Beneficiary Concentration"),
    OFAC_LIST_CHECK("Ofac List Check"),
    PEP_LIST_CHECK("Pep List Check"),
    ADVERSE_MEDIA_CHECK("Adverse Media Check"),
    SANCTIONS_COUNTRY_CHECK("Sanctions Country Check"),
    HIGH_RISK_JURISDICTION("High Risk Jurisdiction"),
    NAME_TRANSLITERATION_MATCH("Name Transliteration Match"),
    ALIAS_DETECTION("Alias Detection"),
    CPF_SSN_VALIDATION("Cpf Ssn Validation"),
    PHONE_CARRIER_CHECK("Phone Carrier Check"),
    EMAIL_DOMAIN_AGE("Email Domain Age"),
    ADDRESS_VERIFICATION("Address Verification"),
    IDENTITY_VELOCITY("Identity Velocity"),
    DEVICE_ACCOUNT_RATIO("Device Account Ratio"),
    EMAIL_PHONE_MISMATCH("Email Phone Mismatch"),
    CREDIT_FILE_THIN("Credit File Thin"),
    STRUCTURING_DETECTION("Structuring Detection"),
    LAYERING_PATTERN("Layering Pattern"),
    RAPID_MOVEMENT("Rapid Movement"),
    INTEGRATION_PATTERN("Integration Pattern"),
    CASH_INTENSIVE_RATIO("Cash Intensive Ratio"),
    UNUSUAL_BUSINESS_PATTERN("Unusual Business Pattern"),
    SHELL_COMPANY_INDICATOR("Shell Company Indicator"),
    TRADE_BASED_ML_INDICATOR("Trade Based Ml Indicator"),
    SCA_EXEMPTION_TRA("Sca Exemption Tra"),
    SCA_EXEMPTION_LOW_VALUE("Sca Exemption Low Value"),
    SCA_EXEMPTION_TRUSTED_BENEFICIARY("Sca Exemption Trusted Beneficiary"),
    SCA_EXEMPTION_RECURRING("Sca Exemption Recurring"),
    PSD3_COP_NAME_MATCH("Psd3 Cop Name Match"),
    DORA_INCIDENT_SEVERITY("Dora Incident Severity"),
    EIDAS_ASSURANCE_LEVEL("Eidas Assurance Level"),
    GDPR_DATA_RETENTION_CHECK("Gdpr Data Retention Check"),
    DEVICE_JAILBREAK_ROOTED("Device Jailbreak Rooted"),
    EMULATOR_DETECTION("Emulator Detection"),
    VPN_PROXY_DETECTION("Vpn Proxy Detection"),
    TOR_EXIT_NODE("Tor Exit Node"),
    BROWSER_INCONSISTENCY("Browser Inconsistency"),
    TIMEZONE_MISMATCH("Timezone Mismatch"),
    LANGUAGE_MISMATCH("Language Mismatch"),
    MCC_HIGH_RISK("Mcc High Risk"),
    MCC_GAMBLING("Mcc Gambling"),
    MCC_CRYPTO("Mcc Crypto"),
    MERCHANT_FIRST_SEEN("Merchant First Seen"),
    MERCHANT_COUNTRY_MISMATCH("Merchant Country Mismatch"),
    MERCHANT_CATEGORY_CHANGE("Merchant Category Change"),
    MERCHANT_VELOCITY_SPIKE("Merchant Velocity Spike"),
    PACS008_FIELD_VALIDATION("Pacs008 Field Validation"),
    REMITTANCE_INFO_ANALYSIS("Remittance Info Analysis"),
    PURPOSE_CODE_MISMATCH("Purpose Code Mismatch"),
    UETR_DUPLICATE_CHECK("Uetr Duplicate Check"),
    CREDITOR_NAME_VALIDATION("Creditor Name Validation"),
    STRUCTURED_ADDRESS_CHECK("Structured Address Check"),
    BENFORD_LAW_DEVIATION("Benford Law Deviation"),
    Z_SCORE_GT("Z Score Gt"),
    STANDARD_DEVIATION_GT("Standard Deviation Gt"),
    PERCENTILE_GT("Percentile Gt"),
    COEFFICIENT_VARIATION_GT("Coefficient Variation Gt"),
    TRANSACTION_COUNT_PER_CARD_HOUR("Transaction Count Per Card Hour"),
    TRANSACTION_COUNT_PER_IP_HOUR("Transaction Count Per Ip Hour"),
    TRANSACTION_COUNT_PER_DEVICE_DAY("Transaction Count Per Device Day"),
    TRANSACTION_COUNT_PER_MERCHANT_HOUR("Transaction Count Per Merchant Hour"),
    TRANSACTION_COUNT_PER_CUSTOMER_HOUR("Transaction Count Per Customer Hour"),
    UNIQUE_CARD_COUNT_PER_IP_HOUR("Unique Card Count Per Ip Hour"),
    UNIQUE_MERCHANT_COUNT_PER_CARD_DAY("Unique Merchant Count Per Card Day"),
    TRANSACTION_ATTEMPT_COUNT_PER_CARD("Transaction Attempt Count Per Card"),
    CVV_FAILURE_VELOCITY("Cvv Failure Velocity"),
    ADDRESS_CHANGE_VELOCITY("Address Change Velocity"),
    BENEFICIARY_ADD_VELOCITY("Beneficiary Add Velocity"),
    CARD_ADD_VELOCITY("Card Add Velocity"),
    AMOUNT_SUM_PER_CARD_HOUR("Amount Sum Per Card Hour"),
    AMOUNT_SUM_PER_CUSTOMER_DAY("Amount Sum Per Customer Day"),
    AVG_TRANSACTION_SPIKE("Avg Transaction Spike"),
    LARGE_AMOUNT_FREQUENCY("Large Amount Frequency"),
    SMALL_AMOUNT_VELOCITY("Small Amount Velocity"),
    ROUND_AMOUNT_FREQUENCY("Round Amount Frequency"),
    SEQUENTIAL_AMOUNT_PATTERN("Sequential Amount Pattern"),
    AMOUNT_VARIANCE_ANOMALY("Amount Variance Anomaly"),
    DAILY_LIMIT_PROXIMITY("Daily Limit Proximity"),
    WEEKLY_LIMIT_PROXIMITY("Weekly Limit Proximity"),
    TIME_BETWEEN_CONSECUTIVE_TX("Time Between Consecutive Tx"),
    TRANSACTION_FREQUENCY_ANOMALY("Transaction Frequency Anomaly"),
    TIME_OF_DAY_ANOMALY("Time Of Day Anomaly"),
    DORMANCY_ALERT_VELOCITY("Dormancy Alert Velocity"),
    WEEKEND_VS_WEEKDAY_PATTERN("Weekend Vs Weekday Pattern"),
    HOLIDAY_TRANSACTION_SPIKE("Holiday Transaction Spike"),
    NIGHTTIME_TRANSACTION_RATIO("Nighttime Transaction Ratio"),
    BUSINESS_HOURS_DEVIATION("Business Hours Deviation"),
    DEVICE_TRUST_SCORE("Device Trust Score"),
    CANVAS_FINGERPRINT_MISMATCH("Canvas Fingerprint Mismatch"),
    WEBGL_FINGERPRINT_ANOMALY("Webgl Fingerprint Anomaly"),
    AUDIO_FINGERPRINT_NEW("Audio Fingerprint New"),
    FONTS_FINGERPRINT_ANOMALY("Fonts Fingerprint Anomaly"),
    SCREEN_RESOLUTION_CHANGE("Screen Resolution Change"),
    BATTERY_LEVEL_ANOMALY("Battery Level Anomaly"),
    HARDWARE_CONCURRENCY_MISMATCH("Hardware Concurrency Mismatch"),
    TOUCH_SUPPORT_INCONSISTENCY("Touch Support Inconsistency"),
    DEVICE_MEMORY_ANOMALY("Device Memory Anomaly"),
    BEHAVIORAL_BASELINE_DEVIATION("Behavioral Baseline Deviation"),
    SPENDING_CATEGORY_SHIFT("Spending Category Shift"),
    TRANSACTION_SIZE_ESCALATION("Transaction Size Escalation"),
    FREQUENCY_PATTERN_CHANGE("Frequency Pattern Change"),
    TIME_PREFERENCE_SHIFT("Time Preference Shift"),
    CHANNEL_USAGE_ANOMALY("Channel Usage Anomaly"),
    PAYMENT_METHOD_SWITCH("Payment Method Switch"),
    RECIPIENT_DIVERSITY_CHANGE("Recipient Diversity Change"),
    GEOGRAPHIC_BEHAVIOR_SHIFT("Geographic Behavior Shift"),
    SESSION_BEHAVIOR_ANOMALY("Session Behavior Anomaly"),
    LOGIN_PATTERN_DEVIATION("Login Pattern Deviation"),
    NAVIGATION_PATTERN_ANOMALY("Navigation Pattern Anomaly"),
    TRANSACTION_TIMING_CLUSTER("Transaction Timing Cluster"),
    AMOUNT_ROUNDING_BEHAVIOR("Amount Rounding Behavior"),
    SPLIT_PAYMENT_PATTERN("Split Payment Pattern"),
    CHI_SQUARE_DISTRIBUTION_TEST("Chi Square Distribution Test"),
    KOLMOGOROV_SMIRNOV_TEST("Kolmogorov Smirnov Test"),
    ANDERSON_DARLING_TEST("Anderson Darling Test"),
    T_TEST_AMOUNT_DEVIATION("T Test Amount Deviation"),
    MANN_WHITNEY_U_TEST("Mann Whitney U Test"),
    CORRELATION_ANOMALY("Correlation Anomaly"),
    REGRESSION_RESIDUAL_OUTLIER("Regression Residual Outlier"),
    VARIANCE_RATIO_TEST("Variance Ratio Test"),
    ENTROPY_SCORE_ANOMALY("Entropy Score Anomaly"),
    SKEWNESS_KURTOSIS_ANOMALY("Skewness Kurtosis Anomaly"),
    MCC_CATEGORY_VELOCITY("Mcc Category Velocity"),
    MCC_SPENDING_LIMIT_CHECK("Mcc Spending Limit Check"),
    MCC_CROSS_CATEGORY_PATTERN("Mcc Cross Category Pattern"),
    MERCHANT_REPUTATION_SCORE("Merchant Reputation Score"),
    MERCHANT_AGE_CHECK("Merchant Age Check"),
    MERCHANT_TRANSACTION_VOLUME("Merchant Transaction Volume"),
    MERCHANT_CHARGEBACK_HISTORY("Merchant Chargeback History"),
    MERCHANT_FRAUD_RATE_CHECK("Merchant Fraud Rate Check"),
    MERCHANT_GEOGRAPHIC_SPREAD("Merchant Geographic Spread"),
    MERCHANT_CUSTOMER_CONCENTRATION("Merchant Customer Concentration"),
    MERCHANT_AMOUNT_DISTRIBUTION("Merchant Amount Distribution"),
    MERCHANT_TIME_PATTERN("Merchant Time Pattern"),
    MERCHANT_DEVICE_DIVERSITY("Merchant Device Diversity"),
    MERCHANT_REFUND_RATIO("Merchant Refund Ratio"),
    MERCHANT_NEW_CUSTOMER_RATIO("Merchant New Customer Ratio"),
    MERCHANT_DORMANT_REACTIVATION("Merchant Dormant Reactivation"),
    MERCHANT_CROSS_BORDER_RATIO("Merchant Cross Border Ratio"),
    MERCHANT_HIGH_VALUE_FREQUENCY("Merchant High Value Frequency"),
    FATF_PLACEMENT_CASH_INTENSIVE("Fatf Placement Cash Intensive"),
    FATF_PLACEMENT_STRUCTURING("Fatf Placement Structuring"),
    FATF_PLACEMENT_SMURFING("Fatf Placement Smurfing"),
    FATF_PLACEMENT_CURRENCY_EXCHANGE("Fatf Placement Currency Exchange"),
    FATF_PLACEMENT_CASINO_GAMBLING("Fatf Placement Casino Gambling"),
    FATF_LAYERING_RAPID_MOVEMENT("Fatf Layering Rapid Movement"),
    FATF_LAYERING_SHELL_COMPANY("Fatf Layering Shell Company"),
    FATF_LAYERING_OFFSHORE("Fatf Layering Offshore"),
    FATF_LAYERING_WIRE_CHAINS("Fatf Layering Wire Chains"),
    FATF_LAYERING_CONVERTIBLE_INSTRUMENTS("Fatf Layering Convertible Instruments"),
    FATF_INTEGRATION_REAL_ESTATE("Fatf Integration Real Estate"),
    FATF_INTEGRATION_LUXURY_GOODS("Fatf Integration Luxury Goods"),
    FATF_INTEGRATION_BUSINESS_INVESTMENT("Fatf Integration Business Investment"),
    FATF_INTEGRATION_LOAN_REPAYMENT("Fatf Integration Loan Repayment"),
    FATF_TBML_OVER_INVOICING("Fatf Tbml Over Invoicing"),
    FATF_TBML_UNDER_INVOICING("Fatf Tbml Under Invoicing"),
    FATF_TBML_PHANTOM_SHIPPING("Fatf Tbml Phantom Shipping"),
    FATF_TBML_MULTIPLE_INVOICING("Fatf Tbml Multiple Invoicing"),
    FATF_TBML_FALSE_DESCRIPTION("Fatf Tbml False Description"),
    FATF_HAWALA_INFORMAL("Fatf Hawala Informal"),
    FATF_NEW_PAYMENT_EXPLOITATION("Fatf New Payment Exploitation"),
    FATF_CRYPTO_MIXING("Fatf Crypto Mixing"),
    FATF_CRYPTO_ATM_CASHOUT("Fatf Crypto Atm Cashout"),
    FATF_PEP_TRANSACTION("Fatf Pep Transaction"),
    FATF_CORRESPONDENT_LAYERING("Fatf Correspondent Layering"),
    FATF_ROUND_TRIPPING("Fatf Round Tripping"),
    FATF_BLACK_MARKET_EXCHANGE("Fatf Black Market Exchange"),
    FATF_INSURANCE_CASH_VALUE("Fatf Insurance Cash Value"),
    SCA_LOW_VALUE_EXEMPTION("Sca Low Value Exemption"),
    SCA_CONTACTLESS_EXEMPTION("Sca Contactless Exemption"),
    SCA_TRA_EXEMPTION("Sca Tra Exemption"),
    SCA_TRUSTED_BENEFICIARY("Sca Trusted Beneficiary"),
    SCA_RECURRING_TRANSACTION("Sca Recurring Transaction"),
    SCA_MERCHANT_INITIATED("Sca Merchant Initiated"),
    SCA_CORPORATE_PAYMENT("Sca Corporate Payment"),
    SCA_SECURE_CORPORATE_PROTOCOL("Sca Secure Corporate Protocol"),
    SCA_LIABILITY_SHIFT("Sca Liability Shift"),
    SCA_DYNAMIC_3DS_ROUTING("Sca Dynamic 3Ds Routing"),
    SCA_FRAUD_RATE_MONITORING("Sca Fraud Rate Monitoring"),
    SCA_CHALLENGE_MANDATORY("Sca Challenge Mandatory"),
    PLT_BEHAVIOR_SORTED_LISTS("Plt Behavior Sorted Lists"),
    PLT_BUSINESS_RULES_SCENARIO("Plt Business Rules Scenario"),
    PLT_IDENTITY_RESOLUTION("Plt Identity Resolution"),
    PLT_COMPROMISE_MANAGER("Plt Compromise Manager"),
    PLT_INTELLIGENCE_NETWORK("Plt Intelligence Network"),
    PLT_RULES_MODELS_HYBRID("Plt Rules Models Hybrid"),
    PLT_BEHAVIORAL_PROFILING("Plt Behavioral Profiling"),
    PLT_NETWORK_ANALYTICS("Plt Network Analytics"),
    PLT_SAR_AUTOMATED("Plt Sar Automated"),
    PLT_DS2_RULE_ENGINE("Plt Ds2 Rule Engine"),
    PLT_REAL_TIME_DETECTION("Plt Real Time Detection"),
    PLT_NETWORK_ENTITY_RESOLUTION("Plt Network Entity Resolution"),
    PLT_SCENARIO_SCORECARD("Plt Scenario Scorecard"),
    PLT_RADAR_RULE_BACKTESTING("Plt Radar Rule Backtesting"),
    PLT_RADAR_METADATA_MATCHING("Plt Radar Metadata Matching"),
    PLT_RADAR_INLINE_LISTS("Plt Radar Inline Lists"),
    PLT_RADAR_COMPLEX_CONDITIONS("Plt Radar Complex Conditions"),
    PLT_RISK_PROFILE_ASSIGNMENT("Plt Risk Profile Assignment"),
    PLT_CUSTOM_RULE_BUILDER("Plt Custom Rule Builder"),
    PLT_RISK_LIST_COMPARISON("Plt Risk List Comparison"),
    PLT_BACKTESTING_LABELING("Plt Backtesting Labeling"),
    PLT_ML_FRAUD_RISK_OUTCOME("Plt Ml Fraud Risk Outcome"),
    PLT_RISK_SCORE_CALCULATION("Plt Risk Score Calculation"),
    PLT_VELOCITY_FILTERS("Plt Velocity Filters"),
    PLT_LINKING_VELOCITY("Plt Linking Velocity"),
    PLT_BAD_ENTITY_NETWORK("Plt Bad Entity Network"),
    PLT_REVIEWLIST_QUEUE("Plt Reviewlist Queue"),
    PLT_CONSORTIUM_DATA_CHECK("Plt Consortium Data Check"),
    BSL_BUSINESS_INDICATOR("Bsl Business Indicator"),
    BSL_BUSINESS_INDICATOR_COMPONENT("Bsl Business Indicator Component"),
    BSL_INTERNAL_LOSS_MULTIPLIER("Bsl Internal Loss Multiplier"),
    BSL_LOSS_DATA_COLLECTION("Bsl Loss Data Collection"),
    BSL_LOSS_EXCLUSION_APPROVAL("Bsl Loss Exclusion Approval"),
    BSL_BUCKET_CLASSIFICATION("Bsl Bucket Classification"),
    BSL_MARGINAL_COEFFICIENT("Bsl Marginal Coefficient"),
    BSL_LOSS_THRESHOLD_SETTING("Bsl Loss Threshold Setting"),
    BSL_RETENTION_PERIOD("Bsl Retention Period"),
    BSL_RISK_GOVERNANCE("Bsl Risk Governance"),
    BSL_LOSS_EVENT_REPORTING("Bsl Loss Event Reporting"),
    BSL_CONTROL_DEFICIENCY("Bsl Control Deficiency"),
    BSL_KRI_MONITORING("Bsl Kri Monitoring"),
    BSL_SCENARIO_ANALYSIS("Bsl Scenario Analysis"),
    APRIORI_ASSOCIATION("Apriori Association"),
    FPGROWTH_FREQUENT_PATTERNS("Fpgrowth Frequent Patterns"),
    ECLAT_ITEMSET("Eclat Itemset"),
    FUZZY_MEMBERSHIP("Fuzzy Membership"),
    FUZZY_ADAPTIVE_THRESHOLD("Fuzzy Adaptive Threshold"),
    LLM_TRANSACTION_DESCRIPTION_ANALYSIS("Llm Transaction Description Analysis"),
    LLM_GENERATIVE_RULE_SYNTHESIS("Llm Generative Rule Synthesis"),
    LLM_ANOMALY_EXPLANATION_GENERATION("Llm Anomaly Explanation Generation"),
    LLM_CHATBOT_FRAUD_DETECTION("Llm Chatbot Fraud Detection"),
    LLM_DEEPFAKE_VOICE_DETECTION("Llm Deepfake Voice Detection"),
    LLM_SYNTHETIC_IMAGE_DETECTION("Llm Synthetic Image Detection"),
    LLM_EMAIL_PHISHING_ANALYSIS("Llm Email Phishing Analysis"),
    LLM_SOCIAL_ENGINEERING_CLASSIFICATION("Llm Social Engineering Classification"),
    LLM_FRAUD_ALERT_PRIORITIZATION("Llm Fraud Alert Prioritization"),
    LLM_MULTI_MODAL_FRAUD_DETECTION("Llm Multi Modal Fraud Detection"),
    LLM_ADVERSARIAL_ATTACK_RESISTANCE("Llm Adversarial Attack Resistance"),
    LLM_FRAUD_PATTERN_AUTODISCOVERY("Llm Fraud Pattern Autodiscovery"),
    NEO4J_WEAKLY_CONNECTED_COMPONENTS("Neo4J Weakly Connected Components"),
    NEO4J_DEGREE_CENTRALITY("Neo4J Degree Centrality"),
    NEO4J_PAGERANK_FRAUD_SCORE("Neo4J Pagerank Fraud Score"),
    NEO4J_LOUVAIN_COMMUNITY_DETECTION("Neo4J Louvain Community Detection"),
    NEO4J_PAIRWISE_SIMILARITY_PII("Neo4J Pairwise Similarity Pii"),
    NEO4J_ENTITY_RESOLUTION_SHARED_PII("Neo4J Entity Resolution Shared Pii"),
    NEO4J_FRAUD_RING_DETECTION("Neo4J Fraud Ring Detection"),
    NEO4J_MONEY_MULE_NETWORK_ANALYSIS("Neo4J Money Mule Network Analysis"),
    NEO4J_CIRCULAR_TRANSACTION_DETECTION("Neo4J Circular Transaction Detection"),
    NEO4J_FIRST_PARTY_FRAUD_CLUSTERING("Neo4J First Party Fraud Clustering"),
    NEO4J_SECOND_LEVEL_FRAUDSTER_ID("Neo4J Second Level Fraudster Id"),
    NEO4J_BETWEENNESS_CENTRALITY_MULE("Neo4J Betweenness Centrality Mule"),
    NEO4J_LABEL_PROPAGATION_FRAUD_SPREAD("Neo4J Label Propagation Fraud Spread"),
    NEO4J_SHORTEST_PATH_AML_TRACKING("Neo4J Shortest Path Aml Tracking"),
    NEO4J_TRIANGLE_COUNT_COLLUSION("Neo4J Triangle Count Collusion"),
    NEO4J_NODE_SIMILARITY_SYNTHETIC_ID("Neo4J Node Similarity Synthetic Id"),
    NEO4J_GRAPH_EMBEDDING_FRAUD_PREDICTION("Neo4J Graph Embedding Fraud Prediction"),
    NEO4J_TEMPORAL_MOTIF_PATTERN("Neo4J Temporal Motif Pattern"),
    BIOMETRIC_KEYSTROKE_DYNAMICS("Biometric Keystroke Dynamics"),
    BIOMETRIC_MOUSE_MOVEMENT("Biometric Mouse Movement"),
    BIOMETRIC_SCROLL_VELOCITY("Biometric Scroll Velocity"),
    DEVICE_FINGERPRINT_CONSISTENCY_CHECK("Device Fingerprint Consistency Check"),
    ECBSV_SSN_VALIDATION("Ecbsv Ssn Validation"),
    SYNTHETIC_FRAUD_SCORE("Synthetic Fraud Score"),
    INJECTION_ATTACK_DETECTION("Injection Attack Detection"),
    LIVENESS_DETECTION_FACIAL("Liveness Detection Facial"),
    LIVENESS_DETECTION_VOICE("Liveness Detection Voice"),
    ANTI_DETECT_BROWSER_DETECTION("Anti Detect Browser Detection"),
    DOCUMENT_FORGERY_DETECTION("Document Forgery Detection"),
    FACE_TO_ID_PHOTO_MATCHING("Face To Id Photo Matching"),
    ADAPTIVE_BEHAVIORAL_ANALYTICS("Adaptive Behavioral Analytics"),
    SYNTHETIC_ID_LABEL_CORRECTION("Synthetic Id Label Correction"),
    MULTI_LAYERED_SYNTHETIC_ID_CONTROLS("SYN015: Controles multicamada para ID sintético");

    private final String description;

    OperatorType(String description) {
      this.description = description;
    }

    public String getDescription() {
      return description;
    }
  }

  /** Tipos de valor suportados */
  public enum ValueType {
    STRING("Texto"),
    NUMBER("Número"),
    BOOLEAN("Booleano"),
    DATE("Data"),
    TIME("Hora"),
    DATETIME("Data e Hora"),
    ARRAY_STRING("Lista de Textos"),
    ARRAY_NUMBER("Lista de Números"),
    FIELD_REFERENCE("Referência a Campo"),
    EXPRESSION("Expressão Calculada"),
    GEO_POINT("Ponto Geográfico"),
    GEO_POLYGON("Polígono Geográfico");

    private final String description;

    ValueType(String description) {
      this.description = description;
    }

    public String getDescription() {
      return description;
    }
  }
}
