package com.rulex.dto.complex;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/** DTO para condições individuais com suporte a operadores avançados. */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ConditionDTO {

  private UUID id;

  @NotBlank(message = "Nome do campo é obrigatório")
  private String fieldName;

  /** Caminho para campos aninhados (ex: "customer.address.city") */
  private String fieldPath;

  @NotNull(message = "Operador é obrigatório")
  private OperatorType operator;

  @NotNull(message = "Tipo do valor é obrigatório")
  private ValueType valueType;

  /** Valor único para comparação */
  private String valueSingle;

  /** Lista de valores para operadores IN, NOT_IN, etc */
  private List<String> valueArray;

  /** Valor mínimo para operadores BETWEEN */
  private String valueMin;

  /** Valor máximo para operadores BETWEEN */
  private String valueMax;

  /** Referência a outro campo para comparação entre campos */
  private String valueFieldRef;

  /** Expressão calculada (ex: "transactionAmount * 1.1") */
  private String valueExpression;

  /** Se a comparação deve ser case-sensitive (para strings) */
  private Boolean caseSensitive;

  /** Inverte o resultado da condição */
  private Boolean negate;

  private Boolean enabled;

  private Integer position;

  private String description;

  /** Mensagem de erro customizada quando a condição falha */
  private String errorMessage;

  /** Operadores de comparação suportados */
  /**
   * Enum de tipos de operadores sincronizado com ConditionOperator.java
   * Total: 496 operadores
   */
  public enum OperatorType {
    ACCOUNT_AGE_LT_DAYS("Account Age Lt Days"),
    ACCOUNT_AGE_LT_MINUTES("Account Age Lt Minutes"),
    ACCOUNT_LINK_DEPTH("Account Link Depth"),
    ACCOUNT_TAKEOVER_PATTERN("Account Takeover Pattern"),
    ADAPTIVE_BEHAVIORAL_ANALYTICS("Adaptive Behavioral Analytics"),
    ADAPTIVE_PARAMETRIC_THRESHOLD("Adaptive Parametric Threshold"),
    ADDRESS_CHANGE_VELOCITY("Address Change Velocity"),
    ADDRESS_MISMATCH("Address Mismatch"),
    ADDRESS_VERIFICATION("Address Verification"),
    ADVERSE_MEDIA_CHECK("Adverse Media Check"),
    ALIAS_DETECTION("Alias Detection"),
    AMOUNT_ANOMALY("Amount Anomaly"),
    AMOUNT_DEVIATION_FROM_AVG("Amount Deviation From Avg"),
    AMOUNT_ROUNDING_BEHAVIOR("Amount Rounding Behavior"),
    AMOUNT_SPIKE("Amount Spike"),
    AMOUNT_SUM_PER_CARD_HOUR("Amount Sum Per Card Hour"),
    AMOUNT_SUM_PER_CUSTOMER_DAY("Amount Sum Per Customer Day"),
    AMOUNT_VARIANCE_ANOMALY("Amount Variance Anomaly"),
    AND("And"),
    ANDERSON_DARLING_TEST("Anderson Darling Test"),
    ANTI_DETECT_BROWSER_DETECTION("Anti Detect Browser Detection"),
    APP_FRAUD_DETECTION("App Fraud Detection"),
    APRIORI_ASSOCIATION("Apriori Association"),
    ARRAY_CONTAINS("Array Contains"),
    ARRAY_NOT_CONTAINS("Array Not Contains"),
    ARRAY_SIZE_EQ("Array Size Eq"),
    ARRAY_SIZE_GT("Array Size Gt"),
    ARRAY_SIZE_LT("Array Size Lt"),
    AUDIO_FINGERPRINT_NEW("Audio Fingerprint New"),
    AVG_INTERVAL_BETWEEN_TXN("Avg Interval Between Txn"),
    AVG_LAST_N_DAYS("Avg Last N Days"),
    AVG_TRANSACTION_SPIKE("Avg Transaction Spike"),
    BATTERY_LEVEL_ANOMALY("Battery Level Anomaly"),
    BEHAVIORAL_BASELINE_DEVIATION("Behavioral Baseline Deviation"),
    BENEFICIARY_ADD_VELOCITY("Beneficiary Add Velocity"),
    BENEFICIARY_CONCENTRATION("Beneficiary Concentration"),
    BENEFICIARY_REUSE_PATTERN("Beneficiary Reuse Pattern"),
    BENFORD_LAW_DEVIATION("Benford Law Deviation"),
    BETWEEN("Between"),
    BIOMETRIC_KEYSTROKE_DYNAMICS("Biometric Keystroke Dynamics"),
    BIOMETRIC_MOUSE_MOVEMENT("Biometric Mouse Movement"),
    BIOMETRIC_SCROLL_VELOCITY("Biometric Scroll Velocity"),
    BROWSER_INCONSISTENCY("Browser Inconsistency"),
    BSL_BUCKET_CLASSIFICATION("Bsl Bucket Classification"),
    BSL_BUSINESS_INDICATOR("Bsl Business Indicator"),
    BSL_BUSINESS_INDICATOR_COMPONENT("Bsl Business Indicator Component"),
    BSL_CONTROL_DEFICIENCY("Bsl Control Deficiency"),
    BSL_INTERNAL_LOSS_MULTIPLIER("Bsl Internal Loss Multiplier"),
    BSL_KRI_MONITORING("Bsl Kri Monitoring"),
    BSL_LOSS_DATA_COLLECTION("Bsl Loss Data Collection"),
    BSL_LOSS_EVENT_REPORTING("Bsl Loss Event Reporting"),
    BSL_LOSS_EXCLUSION_APPROVAL("Bsl Loss Exclusion Approval"),
    BSL_LOSS_THRESHOLD_SETTING("Bsl Loss Threshold Setting"),
    BSL_MARGINAL_COEFFICIENT("Bsl Marginal Coefficient"),
    BSL_RETENTION_PERIOD("Bsl Retention Period"),
    BSL_RISK_GOVERNANCE("Bsl Risk Governance"),
    BSL_SCENARIO_ANALYSIS("Bsl Scenario Analysis"),
    BUSINESS_HOURS_DEVIATION("Business Hours Deviation"),
    BUST_OUT_PATTERN_DETECTION("Bust Out Pattern Detection"),
    CANVAS_FINGERPRINT_MISMATCH("Canvas Fingerprint Mismatch"),
    CAPTCHA_FAILED("Captcha Failed"),
    CARD_ADD_VELOCITY("Card Add Velocity"),
    CARD_CAPTURE_FRAUD("Card Capture Fraud"),
    CARD_TESTING_RING_DETECTION("Card Testing Ring Detection"),
    CASH_INTENSIVE_RATIO("Cash Intensive Ratio"),
    CHANNEL_SWITCH_PATTERN("Channel Switch Pattern"),
    CHANNEL_USAGE_ANOMALY("Channel Usage Anomaly"),
    CHARGEBACK_RATE_GT("Chargeback Rate Gt"),
    CHI_SQUARE_DISTRIBUTION_TEST("Chi Square Distribution Test"),
    CIRCULAR_PAYMENT_DETECTION("Circular Payment Detection"),
    CIRCULAR_TRANSFER_DETECTION("Circular Transfer Detection"),
    CLICK_VELOCITY_GT("Click Velocity Gt"),
    COEFFICIENT_VARIATION_GT("Coefficient Variation Gt"),
    CONSORTIUM_NEGATIVE_FILE_CHECK("Consortium Negative File Check"),
    CONTAINS("Contains"),
    CONTAINS_SUSPICIOUS_KEYWORDS("Contains Suspicious Keywords"),
    CONTEXT("Context"),
    CORRELATION_ANOMALY("Correlation Anomaly"),
    CORRESPONDENT_ANOMALY("Correspondent Anomaly"),
    COUNT_CRYPTO_TXN_LAST_N_DAYS("Count Crypto Txn Last N Days"),
    COUNT_DISTINCT_ACCOUNTS("Count Distinct Accounts"),
    COUNT_DISTINCT_COUNTRIES_LAST_N_DAYS("Count Distinct Countries Last N Days"),
    COUNT_DISTINCT_COUNTRIES_LAST_N_HOURS("Count Distinct Countries Last N Hours"),
    COUNT_DISTINCT_INSTRUMENTS_LAST_N_DAYS("Count Distinct Instruments Last N Days"),
    COUNT_DISTINCT_MERCHANTS_LAST_N_DAYS("Count Distinct Merchants Last N Days"),
    COUNT_DISTINCT_MERCHANTS_LAST_N_HOURS("Count Distinct Merchants Last N Hours"),
    COUNT_DISTINCT_PANS_LAST_N_HOURS("Count Distinct Pans Last N Hours"),
    COUNT_DISTINCT_PAYERS_LAST_N_DAYS("Count Distinct Payers Last N Days"),
    COUNT_DISTINCT_USER_AGENTS_LAST_N_HOURS("Count Distinct User Agents Last N Hours"),
    COUNT_FAILURES_LAST_N_HOURS("Count Failures Last N Hours"),
    COUNT_LAST_N_DAYS("Count Last N Days"),
    COUNT_LAST_N_HOURS("Count Last N Hours"),
    COUNT_MFA_ABANDONMENTS("Count Mfa Abandonments"),
    COUNT_MFA_DENIALS_LAST_N_HOURS("Count Mfa Denials Last N Hours"),
    COUNT_UNIQUE_BENEFICIARIES_LAST_N_DAYS("Count Unique Beneficiaries Last N Days"),
    COUNT_UNIQUE_IPS_LAST_N_HOURS("Count Unique Ips Last N Hours"),
    CPF_SSN_VALIDATION("Cpf Ssn Validation"),
    CREDITOR_NAME_VALIDATION("Creditor Name Validation"),
    CREDIT_FILE_THIN("Credit File Thin"),
    CROSS_BORDER_VELOCITY("Cross Border Velocity"),
    CRYPTO_PUMP_DUMP_DETECTION("Crypto Pump Dump Detection"),
    CVV_FAILURE_VELOCITY("Cvv Failure Velocity"),
    DAILY_LIMIT_PROXIMITY("Daily Limit Proximity"),
    DATE_AFTER("Date After"),
    DATE_BEFORE("Date Before"),
    DATE_BETWEEN("Date Between"),
    DAYS_SINCE_LAST_ACTIVITY("Days Since Last Activity"),
    DAY_OF_WEEK_IN("Day Of Week In"),
    DECIMAL_PLACES_GT("Decimal Places Gt"),
    DEVICE_ACCOUNT_RATIO("Device Account Ratio"),
    DEVICE_CHANGED_IN_SESSION("Device Changed In Session"),
    DEVICE_FINGERPRINT_CONSISTENCY_CHECK("Device Fingerprint Consistency Check"),
    DEVICE_FINGERPRINT_MISMATCH("Device Fingerprint Mismatch"),
    DEVICE_JAILBREAK_ROOTED("Device Jailbreak Rooted"),
    DEVICE_MEMORY_ANOMALY("Device Memory Anomaly"),
    DEVICE_TRUST_SCORE("Device Trust Score"),
    DISTANCE_FROM_LAST_GT("Distance From Last Gt"),
    DOCUMENT_FORGERY_DETECTION("Document Forgery Detection"),
    DOMAIN_IN_LIST("Domain In List"),
    DORA_INCIDENT_SEVERITY("Dora Incident Severity"),
    DORMANCY_ALERT_VELOCITY("Dormancy Alert Velocity"),
    DORMANCY_REVIVAL("Dormancy Revival"),
    ECBSV_SSN_VALIDATION("Ecbsv Ssn Validation"),
    ECLAT_ITEMSET("Eclat Itemset"),
    ECOMMERCE_NO_AVS("Ecommerce No Avs"),
    EIDAS_ASSURANCE_LEVEL("Eidas Assurance Level"),
    EMAIL_DOMAIN_AGE("Email Domain Age"),
    EMAIL_DOMAIN_AGE_LT_DAYS("Email Domain Age Lt Days"),
    EMAIL_PHONE_MISMATCH("Email Phone Mismatch"),
    EMULATOR_DETECTION("Emulator Detection"),
    EMV_SECURITY_CHECK("Emv Security Check"),
    ENDS_WITH("Ends With"),
    ENTROPY_SCORE_ANOMALY("Entropy Score Anomaly"),
    EQ("Eq"),
    EXPIRED_CARD("Expired Card"),
    EXPIRES_WITHIN_DAYS("Expires Within Days"),
    FACE_TO_ID_PHOTO_MATCHING("Face To Id Photo Matching"),
    FAN_IN_COUNT("Fan In Count"),
    FAN_OUT_COUNT("Fan Out Count"),
    FATF_BLACK_MARKET_EXCHANGE("Fatf Black Market Exchange"),
    FATF_CORRESPONDENT_LAYERING("Fatf Correspondent Layering"),
    FATF_CRYPTO_ATM_CASHOUT("Fatf Crypto Atm Cashout"),
    FATF_CRYPTO_MIXING("Fatf Crypto Mixing"),
    FATF_HAWALA_INFORMAL("Fatf Hawala Informal"),
    FATF_INSURANCE_CASH_VALUE("Fatf Insurance Cash Value"),
    FATF_INTEGRATION_BUSINESS_INVESTMENT("Fatf Integration Business Investment"),
    FATF_INTEGRATION_LOAN_REPAYMENT("Fatf Integration Loan Repayment"),
    FATF_INTEGRATION_LUXURY_GOODS("Fatf Integration Luxury Goods"),
    FATF_INTEGRATION_REAL_ESTATE("Fatf Integration Real Estate"),
    FATF_LAYERING_CONVERTIBLE_INSTRUMENTS("Fatf Layering Convertible Instruments"),
    FATF_LAYERING_OFFSHORE("Fatf Layering Offshore"),
    FATF_LAYERING_RAPID_MOVEMENT("Fatf Layering Rapid Movement"),
    FATF_LAYERING_SHELL_COMPANY("Fatf Layering Shell Company"),
    FATF_LAYERING_WIRE_CHAINS("Fatf Layering Wire Chains"),
    FATF_NEW_PAYMENT_EXPLOITATION("Fatf New Payment Exploitation"),
    FATF_PEP_TRANSACTION("Fatf Pep Transaction"),
    FATF_PLACEMENT_CASH_INTENSIVE("Fatf Placement Cash Intensive"),
    FATF_PLACEMENT_CASINO_GAMBLING("Fatf Placement Casino Gambling"),
    FATF_PLACEMENT_CURRENCY_EXCHANGE("Fatf Placement Currency Exchange"),
    FATF_PLACEMENT_SMURFING("Fatf Placement Smurfing"),
    FATF_PLACEMENT_STRUCTURING("Fatf Placement Structuring"),
    FATF_ROUND_TRIPPING("Fatf Round Tripping"),
    FATF_TBML_FALSE_DESCRIPTION("Fatf Tbml False Description"),
    FATF_TBML_MULTIPLE_INVOICING("Fatf Tbml Multiple Invoicing"),
    FATF_TBML_OVER_INVOICING("Fatf Tbml Over Invoicing"),
    FATF_TBML_PHANTOM_SHIPPING("Fatf Tbml Phantom Shipping"),
    FATF_TBML_UNDER_INVOICING("Fatf Tbml Under Invoicing"),
    FIELD_EQ("Field Eq"),
    FIELD_GT("Field Gt"),
    FIELD_GTE("Field Gte"),
    FIELD_LT("Field Lt"),
    FIELD_LTE("Field Lte"),
    FIELD_NEQ("Field Neq"),
    FONTS_FINGERPRINT_ANOMALY("Fonts Fingerprint Anomaly"),
    FPGROWTH_FREQUENT_PATTERNS("Fpgrowth Frequent Patterns"),
    FRAUD("Fraud"),
    FREQUENCY_PATTERN_CHANGE("Frequency Pattern Change"),
    FUZZY_ADAPTIVE_THRESHOLD("Fuzzy Adaptive Threshold"),
    FUZZY_MEMBERSHIP("Fuzzy Membership"),
    GDPR_DATA_RETENTION_CHECK("Gdpr Data Retention Check"),
    GEOGRAPHIC_BEHAVIOR_SHIFT("Geographic Behavior Shift"),
    GEO_DISTANCE_GT("Geo Distance Gt"),
    GEO_DISTANCE_LT("Geo Distance Lt"),
    GEO_IN_POLYGON("Geo In Polygon"),
    GT("Gt"),
    GTE("Gte"),
    GTE_PERCENT_OF_LAST_INCOMING("Gte Percent Of Last Incoming"),
    GT_CURRENT_DATE("Gt Current Date"),
    GT_FIELD_MULTIPLIER("Gt Field Multiplier"),
    HARDWARE_CONCURRENCY_MISMATCH("Hardware Concurrency Mismatch"),
    HAS_FAILED_3DS_LAST_N_MINUTES("Has Failed 3Ds Last N Minutes"),
    HAS_INCOMING_TRANSFER_LAST_N_HOURS("Has Incoming Transfer Last N Hours"),
    HIGH_RISK_CORRIDOR_CHECK("High Risk Corridor Check"),
    HIGH_RISK_JURISDICTION("High Risk Jurisdiction"),
    HOLIDAY_TRANSACTION_SPIKE("Holiday Transaction Spike"),
    HOUR_BETWEEN("Hour Between"),
    IDENTITY_VELOCITY("Identity Velocity"),
    IMPOSSIBLE_TRAVEL("Impossible Travel"),
    IN("In"),
    INJECTION_ATTACK_DETECTION("Injection Attack Detection"),
    INTEGRATION_PATTERN("Integration Pattern"),
    INVESTMENT_SCAM_PATTERN("Investment Scam Pattern"),
    IN_CUSTOMER_CHARGEBACK_MERCHANTS("In Customer Chargeback Merchants"),
    IN_CUSTOMER_HISTORY("In Customer History"),
    IN_CUSTOMER_USUAL_HOURS("In Customer Usual Hours"),
    IN_LIST("In List"),
    IS_CRYPTO_RANSOM_AMOUNT("Is Crypto Ransom Amount"),
    IS_FALSE("Is False"),
    IS_FIRST("Is First"),
    IS_HOLIDAY("Is Holiday"),
    IS_IMPOSSIBLE_COMBINATION("Is Impossible Combination"),
    IS_NEW("Is New"),
    IS_NEW_DEVICE("Is New Device"),
    IS_NEW_LOCATION("Is New Location"),
    IS_NULL("Is Null"),
    IS_TRUE("Is True"),
    IS_VOIP("Is Voip"),
    IS_WEEKEND("Is Weekend"),
    KOLMOGOROV_SMIRNOV_TEST("Kolmogorov Smirnov Test"),
    LANGUAGE_MISMATCH("Language Mismatch"),
    LARGE_AMOUNT_FREQUENCY("Large Amount Frequency"),
    LAYERED_TRANSFER_PATTERN("Layered Transfer Pattern"),
    LAYERING_PATTERN("Layering Pattern"),
    LIVENESS_DETECTION_FACIAL("Liveness Detection Facial"),
    LIVENESS_DETECTION_VOICE("Liveness Detection Voice"),
    LLM_ADVERSARIAL_ATTACK_RESISTANCE("Llm Adversarial Attack Resistance"),
    LLM_ANOMALY_EXPLANATION_GENERATION("Llm Anomaly Explanation Generation"),
    LLM_CHATBOT_FRAUD_DETECTION("Llm Chatbot Fraud Detection"),
    LLM_DEEPFAKE_VOICE_DETECTION("Llm Deepfake Voice Detection"),
    LLM_EMAIL_PHISHING_ANALYSIS("Llm Email Phishing Analysis"),
    LLM_FRAUD_ALERT_PRIORITIZATION("Llm Fraud Alert Prioritization"),
    LLM_FRAUD_PATTERN_AUTODISCOVERY("Llm Fraud Pattern Autodiscovery"),
    LLM_GENERATIVE_RULE_SYNTHESIS("Llm Generative Rule Synthesis"),
    LLM_MULTI_MODAL_FRAUD_DETECTION("Llm Multi Modal Fraud Detection"),
    LLM_SOCIAL_ENGINEERING_CLASSIFICATION("Llm Social Engineering Classification"),
    LLM_SYNTHETIC_IMAGE_DETECTION("Llm Synthetic Image Detection"),
    LLM_TRANSACTION_DESCRIPTION_ANALYSIS("Llm Transaction Description Analysis"),
    LOCATION_DEVIATION("Location Deviation"),
    LOGIN_PATTERN_DEVIATION("Login Pattern Deviation"),
    LT("Lt"),
    LTE("Lte"),
    LT_CURRENT_DATE("Lt Current Date"),
    MANN_WHITNEY_U_TEST("Mann Whitney U Test"),
    MAX_AMOUNT_LAST_N_DAYS("Max Amount Last N Days"),
    MCC_ANOMALY("Mcc Anomaly"),
    MCC_CATEGORY_VELOCITY("Mcc Category Velocity"),
    MCC_CROSS_CATEGORY_PATTERN("Mcc Cross Category Pattern"),
    MCC_CRYPTO("Mcc Crypto"),
    MCC_GAMBLING("Mcc Gambling"),
    MCC_HIGH_RISK("Mcc High Risk"),
    MCC_SPENDING_LIMIT_CHECK("Mcc Spending Limit Check"),
    MERCHANT_AGE_CHECK("Merchant Age Check"),
    MERCHANT_AMOUNT_DISTRIBUTION("Merchant Amount Distribution"),
    MERCHANT_ANOMALY("Merchant Anomaly"),
    MERCHANT_CATEGORY_CHANGE("Merchant Category Change"),
    MERCHANT_CHARGEBACK_HISTORY("Merchant Chargeback History"),
    MERCHANT_COUNTRY_MISMATCH("Merchant Country Mismatch"),
    MERCHANT_CROSS_BORDER_RATIO("Merchant Cross Border Ratio"),
    MERCHANT_CUSTOMER_CONCENTRATION("Merchant Customer Concentration"),
    MERCHANT_DEVIATION("Merchant Deviation"),
    MERCHANT_DEVICE_DIVERSITY("Merchant Device Diversity"),
    MERCHANT_DORMANT_REACTIVATION("Merchant Dormant Reactivation"),
    MERCHANT_FIRST_SEEN("Merchant First Seen"),
    MERCHANT_FRAUD_RATE_CHECK("Merchant Fraud Rate Check"),
    MERCHANT_GEOGRAPHIC_SPREAD("Merchant Geographic Spread"),
    MERCHANT_HIGH_VALUE_FREQUENCY("Merchant High Value Frequency"),
    MERCHANT_NEW_CUSTOMER_RATIO("Merchant New Customer Ratio"),
    MERCHANT_REFUND_RATIO("Merchant Refund Ratio"),
    MERCHANT_REPUTATION_SCORE("Merchant Reputation Score"),
    MERCHANT_TIME_PATTERN("Merchant Time Pattern"),
    MERCHANT_TRANSACTION_VOLUME("Merchant Transaction Volume"),
    MERCHANT_VELOCITY_SPIKE("Merchant Velocity Spike"),
    MICRO_DEPOSIT_VELOCITY("Micro Deposit Velocity"),
    MICRO_TRANSACTION_TEST("Micro Transaction Test"),
    MIN_AMOUNT_LAST_N_DAYS("Min Amount Last N Days"),
    MOD_EQ("Mod Eq"),
    MOD_NEQ("Mod Neq"),
    MOUSE_MOVEMENT_ANOMALY("Mouse Movement Anomaly"),
    MULTI_LAYERED_SYNTHETIC_ID_CONTROLS("Multi Layered Synthetic Id Controls"),
    NAME_SIMILARITY_GT("Name Similarity Gt"),
    NAME_SIMILARITY_LT("Name Similarity Lt"),
    NAME_TRANSLITERATION_MATCH("Name Transliteration Match"),
    NAND("Nand"),
    NAVIGATION_PATTERN_ANOMALY("Navigation Pattern Anomaly"),
    NEO4J_BETWEENNESS_CENTRALITY_MULE("Neo4J Betweenness Centrality Mule"),
    NEO4J_CIRCULAR_TRANSACTION_DETECTION("Neo4J Circular Transaction Detection"),
    NEO4J_DEGREE_CENTRALITY("Neo4J Degree Centrality"),
    NEO4J_ENTITY_RESOLUTION_SHARED_PII("Neo4J Entity Resolution Shared Pii"),
    NEO4J_FIRST_PARTY_FRAUD_CLUSTERING("Neo4J First Party Fraud Clustering"),
    NEO4J_FRAUD_RING_DETECTION("Neo4J Fraud Ring Detection"),
    NEO4J_GRAPH_EMBEDDING_FRAUD_PREDICTION("Neo4J Graph Embedding Fraud Prediction"),
    NEO4J_LABEL_PROPAGATION_FRAUD_SPREAD("Neo4J Label Propagation Fraud Spread"),
    NEO4J_LOUVAIN_COMMUNITY_DETECTION("Neo4J Louvain Community Detection"),
    NEO4J_MONEY_MULE_NETWORK_ANALYSIS("Neo4J Money Mule Network Analysis"),
    NEO4J_NODE_SIMILARITY_SYNTHETIC_ID("Neo4J Node Similarity Synthetic Id"),
    NEO4J_PAGERANK_FRAUD_SCORE("Neo4J Pagerank Fraud Score"),
    NEO4J_PAIRWISE_SIMILARITY_PII("Neo4J Pairwise Similarity Pii"),
    NEO4J_SECOND_LEVEL_FRAUDSTER_ID("Neo4J Second Level Fraudster Id"),
    NEO4J_SHORTEST_PATH_AML_TRACKING("Neo4J Shortest Path Aml Tracking"),
    NEO4J_TEMPORAL_MOTIF_PATTERN("Neo4J Temporal Motif Pattern"),
    NEO4J_TRIANGLE_COUNT_COLLUSION("Neo4J Triangle Count Collusion"),
    NEO4J_WEAKLY_CONNECTED_COMPONENTS("Neo4J Weakly Connected Components"),
    NEQ("Neq"),
    NESTED_CORRESPONDENT_CHECK("Nested Correspondent Check"),
    NIGHTTIME_TRANSACTION_RATIO("Nighttime Transaction Ratio"),
    NOR("Nor"),
    NOT("Not"),
    NOT_BETWEEN("Not Between"),
    NOT_CONTAINS("Not Contains"),
    NOT_IN("Not In"),
    NOT_IN_CUSTOMER_HISTORY("Not In Customer History"),
    NOT_IN_CUSTOMER_USUAL_HOURS("Not In Customer Usual Hours"),
    NOT_IN_HISTORICAL("Not In Historical"),
    NOT_IN_LIST("Not In List"),
    NOT_NULL("Not Null"),
    NOT_REGEX("Not Regex"),
    OFAC_LIST_CHECK("Ofac List Check"),
    OFFLINE_PIN_FAILED("Offline Pin Failed"),
    OR("Or"),
    OUTFLOW_RATE_LAST_N_DAYS("Outflow Rate Last N Days"),
    PACS008_FIELD_VALIDATION("Pacs008 Field Validation"),
    PATTERN_ESCALATION("Pattern Escalation"),
    PATTERN_ROUND_NUMBERS("Pattern Round Numbers"),
    PATTERN_SPLIT_TRANSACTION("Pattern Split Transaction"),
    PAYMENT_METHOD_SWITCH("Payment Method Switch"),
    PEER_GROUP_DEVIATION_SCORE("Peer Group Deviation Score"),
    PEP_LIST_CHECK("Pep List Check"),
    PERCENTAGE_OF_FIELD("Percentage Of Field"),
    PERCENTILE_GT("Percentile Gt"),
    PHONE_CARRIER_CHECK("Phone Carrier Check"),
    PHONE_COUNTRY_MISMATCH("Phone Country Mismatch"),
    PIG_BUTCHERING_INDICATOR("Pig Butchering Indicator"),
    PIN_CVV_LIMIT_EXCEEDED("Pin Cvv Limit Exceeded"),
    PIX_KEY_CHANGED_LAST_N_DAYS("Pix Key Changed Last N Days"),
    PLT_BACKTESTING_LABELING("Plt Backtesting Labeling"),
    PLT_BAD_ENTITY_NETWORK("Plt Bad Entity Network"),
    PLT_BEHAVIORAL_PROFILING("Plt Behavioral Profiling"),
    PLT_BEHAVIOR_SORTED_LISTS("Plt Behavior Sorted Lists"),
    PLT_BUSINESS_RULES_SCENARIO("Plt Business Rules Scenario"),
    PLT_COMPROMISE_MANAGER("Plt Compromise Manager"),
    PLT_CONSORTIUM_DATA_CHECK("Plt Consortium Data Check"),
    PLT_CUSTOM_RULE_BUILDER("Plt Custom Rule Builder"),
    PLT_DS2_RULE_ENGINE("Plt Ds2 Rule Engine"),
    PLT_IDENTITY_RESOLUTION("Plt Identity Resolution"),
    PLT_INTELLIGENCE_NETWORK("Plt Intelligence Network"),
    PLT_LINKING_VELOCITY("Plt Linking Velocity"),
    PLT_ML_FRAUD_RISK_OUTCOME("Plt Ml Fraud Risk Outcome"),
    PLT_NETWORK_ANALYTICS("Plt Network Analytics"),
    PLT_NETWORK_ENTITY_RESOLUTION("Plt Network Entity Resolution"),
    PLT_RADAR_COMPLEX_CONDITIONS("Plt Radar Complex Conditions"),
    PLT_RADAR_INLINE_LISTS("Plt Radar Inline Lists"),
    PLT_RADAR_METADATA_MATCHING("Plt Radar Metadata Matching"),
    PLT_RADAR_RULE_BACKTESTING("Plt Radar Rule Backtesting"),
    PLT_REAL_TIME_DETECTION("Plt Real Time Detection"),
    PLT_REVIEWLIST_QUEUE("Plt Reviewlist Queue"),
    PLT_RISK_LIST_COMPARISON("Plt Risk List Comparison"),
    PLT_RISK_PROFILE_ASSIGNMENT("Plt Risk Profile Assignment"),
    PLT_RISK_SCORE_CALCULATION("Plt Risk Score Calculation"),
    PLT_RULES_MODELS_HYBRID("Plt Rules Models Hybrid"),
    PLT_SAR_AUTOMATED("Plt Sar Automated"),
    PLT_SCENARIO_SCORECARD("Plt Scenario Scorecard"),
    PLT_VELOCITY_FILTERS("Plt Velocity Filters"),
    POS_SECURITY_MISSING("Pos Security Missing"),
    PSD3_COP_NAME_MATCH("Psd3 Cop Name Match"),
    PURPOSE_CODE_MISMATCH("Purpose Code Mismatch"),
    RAPID_MOVEMENT("Rapid Movement"),
    RAPID_MULTI_HOP("Rapid Multi Hop"),
    RAPID_SUCCESSION_PATTERN("Rapid Succession Pattern"),
    REAL_TIME_RISK_SCORING("Real Time Risk Scoring"),
    RECIPIENT_DIVERSITY_CHANGE("Recipient Diversity Change"),
    RECIPIENT_IN_WATCHLIST("Recipient In Watchlist"),
    RECIPIENT_IS_NEW("Recipient Is New"),
    REGEX("Regex"),
    REGRESSION_RESIDUAL_OUTLIER("Regression Residual Outlier"),
    REMITTANCE_INFO_ANALYSIS("Remittance Info Analysis"),
    ROMANCE_SCAM_INDICATOR("Romance Scam Indicator"),
    ROUND_AMOUNT("Round Amount"),
    ROUND_AMOUNT_FREQUENCY("Round Amount Frequency"),
    ROUND_TRIP_DETECTION("Round Trip Detection"),
    SANCTIONS_COUNTRY_CHECK("Sanctions Country Check"),
    SCA_CHALLENGE_MANDATORY("Sca Challenge Mandatory"),
    SCA_CONTACTLESS_EXEMPTION("Sca Contactless Exemption"),
    SCA_CORPORATE_PAYMENT("Sca Corporate Payment"),
    SCA_DYNAMIC_3DS_ROUTING("Sca Dynamic 3Ds Routing"),
    SCA_EXEMPTION_LOW_VALUE("Sca Exemption Low Value"),
    SCA_EXEMPTION_RECURRING("Sca Exemption Recurring"),
    SCA_EXEMPTION_TRA("Sca Exemption Tra"),
    SCA_EXEMPTION_TRUSTED_BENEFICIARY("Sca Exemption Trusted Beneficiary"),
    SCA_FRAUD_RATE_MONITORING("Sca Fraud Rate Monitoring"),
    SCA_LIABILITY_SHIFT("Sca Liability Shift"),
    SCA_LOW_VALUE_EXEMPTION("Sca Low Value Exemption"),
    SCA_MERCHANT_INITIATED("Sca Merchant Initiated"),
    SCA_RECURRING_TRANSACTION("Sca Recurring Transaction"),
    SCA_SECURE_CORPORATE_PROTOCOL("Sca Secure Corporate Protocol"),
    SCA_TRA_EXEMPTION("Sca Tra Exemption"),
    SCA_TRUSTED_BENEFICIARY("Sca Trusted Beneficiary"),
    SCREEN_RESOLUTION_CHANGE("Screen Resolution Change"),
    SECURITY("Security"),
    SEGMENT_OF_ONE_PROFILING("Segment Of One Profiling"),
    SEQUENTIAL_AMOUNT_PATTERN("Sequential Amount Pattern"),
    SESSION_BEHAVIOR_ANOMALY("Session Behavior Anomaly"),
    SESSION_DURATION_LT("Session Duration Lt"),
    SHARED_DEVICE_COUNT("Shared Device Count"),
    SHARED_IP_COUNT("Shared Ip Count"),
    SHELL_BANK_INDICATOR("Shell Bank Indicator"),
    SHELL_COMPANY_INDICATOR("Shell Company Indicator"),
    SKEWNESS_KURTOSIS_ANOMALY("Skewness Kurtosis Anomaly"),
    SMALL_AMOUNT_VELOCITY("Small Amount Velocity"),
    SPENDING_CATEGORY_SHIFT("Spending Category Shift"),
    SPLIT_PAYMENT_PATTERN("Split Payment Pattern"),
    SPLIT_TRANSACTION_DETECTION("Split Transaction Detection"),
    STANDARD_DEVIATION_GT("Standard Deviation Gt"),
    STARTS_WITH("Starts With"),
    STAT_ANOVA_F_TEST("Stat Anova F Test"),
    STAT_BOOTSTRAP_CONFIDENCE_INTERVAL("Stat Bootstrap Confidence Interval"),
    STAT_DBSCAN_NOISE_DETECTION("Stat Dbscan Noise Detection"),
    STAT_DIXON_Q_TEST("Stat Dixon Q Test"),
    STAT_GMM_PROBABILITY("Stat Gmm Probability"),
    STAT_GRUBBS_TEST("Stat Grubbs Test"),
    STAT_ISOLATION_FOREST_SCORE("Stat Isolation Forest Score"),
    STAT_KMEANS_CLUSTER_DISTANCE("Stat Kmeans Cluster Distance"),
    STAT_KRUSKAL_WALLIS_TEST("Stat Kruskal Wallis Test"),
    STAT_LEVENE_TEST("Stat Levene Test"),
    STAT_LOCAL_OUTLIER_FACTOR("Stat Local Outlier Factor"),
    STAT_MAHALANOBIS_DISTANCE("Stat Mahalanobis Distance"),
    STAT_ONE_CLASS_SVM_BOUNDARY("Stat One Class Svm Boundary"),
    STAT_SHAPIRO_WILK_TEST("Stat Shapiro Wilk Test"),
    STAT_WELCH_T_TEST("Stat Welch T Test"),
    STRUCTURED_ADDRESS_CHECK("Structured Address Check"),
    STRUCTURING_DETECTION("Structuring Detection"),
    SUM_BY_CHANNEL_LAST_N_DAYS("Sum By Channel Last N Days"),
    SUM_LAST_N_DAYS("Sum Last N Days"),
    SUM_LAST_N_HOURS("Sum Last N Hours"),
    SUSPICIOUS("Suspicious"),
    SUSPICIOUS_TERMINAL("Suspicious Terminal"),
    SUSPICIOUS_TRANSACTION_TYPE("Suspicious Transaction Type"),
    SYNTHETIC_FRAUD_SCORE("Synthetic Fraud Score"),
    SYNTHETIC_IDENTITY_RING("Synthetic Identity Ring"),
    SYNTHETIC_ID_LABEL_CORRECTION("Synthetic Id Label Correction"),
    TERMINAL_VERIFICATION_FAILED("Terminal Verification Failed"),
    TIMEZONE_MISMATCH("Timezone Mismatch"),
    TIME_AFTER("Time After"),
    TIME_ANOMALY("Time Anomaly"),
    TIME_BEFORE("Time Before"),
    TIME_BETWEEN("Time Between"),
    TIME_BETWEEN_CONSECUTIVE_TX("Time Between Consecutive Tx"),
    TIME_DEVIATION_FROM_USUAL("Time Deviation From Usual"),
    TIME_OF_DAY_ANOMALY("Time Of Day Anomaly"),
    TIME_PREFERENCE_SHIFT("Time Preference Shift"),
    TIME_SINCE_LAST_LT("Time Since Last Lt"),
    TOR_EXIT_NODE("Tor Exit Node"),
    TOUCH_SUPPORT_INCONSISTENCY("Touch Support Inconsistency"),
    TRADE_BASED_ML_INDICATOR("Trade Based Ml Indicator"),
    TRANSACTION_ATTEMPT_COUNT_PER_CARD("Transaction Attempt Count Per Card"),
    TRANSACTION_COUNT_PER_CARD_HOUR("Transaction Count Per Card Hour"),
    TRANSACTION_COUNT_PER_CUSTOMER_HOUR("Transaction Count Per Customer Hour"),
    TRANSACTION_COUNT_PER_DEVICE_DAY("Transaction Count Per Device Day"),
    TRANSACTION_COUNT_PER_IP_HOUR("Transaction Count Per Ip Hour"),
    TRANSACTION_COUNT_PER_MERCHANT_HOUR("Transaction Count Per Merchant Hour"),
    TRANSACTION_FREQUENCY_ANOMALY("Transaction Frequency Anomaly"),
    TRANSACTION_SIZE_ESCALATION("Transaction Size Escalation"),
    TRANSACTION_TIMING_CLUSTER("Transaction Timing Cluster"),
    TRANSFER_AMOUNT_GT("Transfer Amount Gt"),
    TRANSFER_VELOCITY_GT("Transfer Velocity Gt"),
    TYPING_SPEED_ANOMALY("Typing Speed Anomaly"),
    T_TEST_AMOUNT_DEVIATION("T Test Amount Deviation"),
    UETR_DUPLICATE_CHECK("Uetr Duplicate Check"),
    UNIQUE_CARD_COUNT_PER_IP_HOUR("Unique Card Count Per Ip Hour"),
    UNIQUE_MERCHANT_COUNT_PER_CARD_DAY("Unique Merchant Count Per Card Day"),
    UNUSUAL_BUSINESS_PATTERN("Unusual Business Pattern"),
    UNUSUAL_CARD_MEDIA("Unusual Card Media"),
    USER_AGENT_SUSPICIOUS("User Agent Suspicious"),
    VARIANCE_RATIO_TEST("Variance Ratio Test"),
    VELOCITY("Velocity"),
    VELOCITY_ACCELERATION("Velocity Acceleration"),
    VELOCITY_ANOMALY("Velocity Anomaly"),
    VELOCITY_AVG_GT("Velocity Avg Gt"),
    VELOCITY_AVG_LT("Velocity Avg Lt"),
    VELOCITY_COUNT_GT("Velocity Count Gt"),
    VELOCITY_COUNT_LT("Velocity Count Lt"),
    VELOCITY_CROSS_CHANNEL("Velocity Cross Channel"),
    VELOCITY_DISTINCT_GT("Velocity Distinct Gt"),
    VELOCITY_DISTINCT_LT("Velocity Distinct Lt"),
    VELOCITY_PERCENTILE("Velocity Percentile"),
    VELOCITY_RATIO_GT("Velocity Ratio Gt"),
    VELOCITY_ROLLING_WINDOW("Velocity Rolling Window"),
    VELOCITY_SPIKE("Velocity Spike"),
    VELOCITY_SUM_GT("Velocity Sum Gt"),
    VELOCITY_SUM_LT("Velocity Sum Lt"),
    VELOCITY_TREND("Velocity Trend"),
    VPN_PROXY_DETECTION("Vpn Proxy Detection"),
    WEBGL_FINGERPRINT_ANOMALY("Webgl Fingerprint Anomaly"),
    WEEKEND_VS_WEEKDAY_PATTERN("Weekend Vs Weekday Pattern"),
    WEEKLY_LIMIT_PROXIMITY("Weekly Limit Proximity"),
    XOR("Xor"),
    Z_SCORE_GT("Z Score Gt");

    private final String description;

    OperatorType(String description) {
      this.description = description;
    }

    public String getDescription() {
      return description;
    }
  }
  public enum ValueType {
    STRING("Texto"),
    NUMBER("Número"),
    BOOLEAN("Booleano"),
    DATE("Data"),
    TIME("Hora"),
    DATETIME("Data e Hora"),
    ARRAY_STRING("Lista de Textos"),
    ARRAY_NUMBER("Lista de Números"),
    FIELD_REFERENCE("Referência a Campo"),
    EXPRESSION("Expressão Calculada"),
    GEO_POINT("Ponto Geográfico"),
    GEO_POLYGON("Polígono Geográfico");

    private final String description;

    ValueType(String description) {
      this.description = description;
    }

    public String getDescription() {
      return description;
    }
  }
}
