/**
 * massiveCatalog.ts
 *
 * Catálogo massivo de 200+ tipos de diagramas do RULEX.
 * Organizado em 13 famílias de notação.
 */

import type { DiagramNotation } from "../types";

export interface MassiveDiagramType {
  notation: DiagramNotation;
  name: string;
  nameEn: string;
  description: string;
  useCase: string;
  tools?: string[];
  example?: string;
}

export interface MassiveDiagramFamily {
  id: string;
  notation: DiagramNotation;
  title: string;
  description: string;
  diagrams: MassiveDiagramType[];
}

export const MASSIVE_DIAGRAM_CATALOG: MassiveDiagramFamily[] = [
  // ============================================================
  // FAMÍLIA 1: Processos & Negócio (30 tipos)
  // ============================================================
  {
    id: "processos",
    notation: "PROCESS",
    title: "Processos & Negócio",
    description: "Fluxogramas, BPMN, decisões e jornadas",
    diagrams: [
      {
        notation: "FLOWCHART",
        name: "Fluxograma",
        nameEn: "Flowchart",
        description: "Representação gráfica de um processo usando símbolos padronizados",
        useCase: "Documentar o fluxo de análise de transação no RULEX",
        tools: ["Mermaid", "draw.io", "Lucidchart"],
      },
      {
        notation: "FLOWCHART",
        name: "Fluxograma ANSI/ISO",
        nameEn: "ANSI/ISO Flowchart",
        description: "Fluxograma seguindo padrões ANSI/ISO",
        useCase: "Documentação formal de processos",
        tools: ["Visio", "Lucidchart"],
      },
      {
        notation: "FLOWCHART",
        name: "Fluxograma Funcional",
        nameEn: "Cross-Functional Flowchart",
        description: "Mostra responsabilidades de cada área no processo",
        useCase: "Mapear handoffs entre Prevenção, Compliance e Operações",
        tools: ["Visio", "Lucidchart"],
      },
      {
        notation: "FLOWCHART",
        name: "Diagrama com Raias",
        nameEn: "Swimlane Diagram",
        description: "Organiza atividades em raias por ator/sistema",
        useCase: "Visualizar quem faz o quê no fluxo de detecção de fraude",
        tools: ["draw.io", "Miro", "Figma"],
      },
      {
        notation: "PROCESS",
        name: "Diagrama de Fluxo de Trabalho",
        nameEn: "Workflow Diagram",
        description: "Sequência de tarefas e decisões",
        useCase: "Automatizar aprovações de regras no RULEX",
        tools: ["Miro", "Monday", "Jira"],
      },
      {
        notation: "PROCESS",
        name: "Diagrama de Fluxo de Processo",
        nameEn: "Process Flow Diagram (PFD)",
        description: "Visão geral de processos industriais/operacionais",
        useCase: "Modelar pipeline de processamento de transações",
        tools: ["Visio", "Lucidchart"],
      },
      {
        notation: "BPMN",
        name: "BPMN - Processo",
        nameEn: "BPMN Process Diagram",
        description: "Notação padrão ISO para processos de negócio",
        useCase: "Documentar o processo completo de análise de fraude",
        tools: ["Camunda Modeler", "Bizagi", "draw.io"],
      },
      {
        notation: "BPMN",
        name: "BPMN - Colaboração",
        nameEn: "BPMN Collaboration Diagram",
        description: "Interação entre múltiplos participantes/pools",
        useCase: "Mapear integração entre RULEX, gateway e banco emissor",
        tools: ["Camunda Modeler", "Bizagi"],
      },
      {
        notation: "BPMN",
        name: "BPMN - Coreografia",
        nameEn: "BPMN Choreography Diagram",
        description: "Troca de mensagens sem processos internos",
        useCase: "Protocolo de comunicação com sistemas externos",
        tools: ["Camunda Modeler"],
      },
      {
        notation: "BPMN",
        name: "BPMN - Conversação",
        nameEn: "BPMN Conversation Diagram",
        description: "Alto nível de troca de mensagens entre participantes",
        useCase: "Visão executiva de integrações",
        tools: ["Camunda Modeler"],
      },
      {
        notation: "BPMN",
        name: "BPMN - Subprocesso de Evento",
        nameEn: "BPMN Event Subprocess",
        description: "Subprocessos acionados por eventos de fronteira",
        useCase: "Tratamento de exceções em regras",
        tools: ["Camunda Modeler"],
      },
      {
        notation: "EPC",
        name: "EPC - Cadeia de Processos Orientada a Eventos",
        nameEn: "Event-driven Process Chain",
        description: "Notação de processos com eventos e funções",
        useCase: "Documentação em ambientes SAP",
        tools: ["ARIS", "Visio"],
      },
      {
        notation: "PROCESS",
        name: "Diagrama SIPOC",
        nameEn: "SIPOC Diagram",
        description: "Supplier–Input–Process–Output–Customer",
        useCase: "Definir escopo do motor de regras para stakeholders",
        tools: ["Miro", "Lucidchart"],
      },
      {
        notation: "PROCESS",
        name: "Mapa de Fluxo de Valor",
        nameEn: "Value Stream Map (VSM)",
        description: "Visualiza fluxo de valor e identifica desperdícios",
        useCase: "Otimizar tempo de resposta do endpoint /analyze",
        tools: ["Lucidchart", "Miro"],
      },
      {
        notation: "PROCESS",
        name: "Service Blueprint",
        nameEn: "Service Blueprint",
        description: "Jornada + processos de backstage e infraestrutura",
        useCase: "Visão completa: UI → API → Serviços → DB → Logs",
        tools: ["Miro", "Figma"],
      },
      {
        notation: "PROCESS",
        name: "Mapa de Jornada do Cliente",
        nameEn: "Customer Journey Map",
        description: "Experiência do usuário através de touchpoints",
        useCase: "Mapear experiência do analista de fraude usando o RULEX",
        tools: ["Figma", "Miro", "UXPressia"],
      },
      {
        notation: "PROCESS",
        name: "Mapa de Histórias",
        nameEn: "Story Map",
        description: "User Story Mapping para planejamento ágil",
        useCase: "Priorizar features do backlog",
        tools: ["Miro", "Mural", "StoriesOnBoard"],
      },
      {
        notation: "MATRIX",
        name: "Matriz RACI",
        nameEn: "RACI Matrix",
        description: "Responsible, Accountable, Consulted, Informed",
        useCase: "Definir papéis na implementação de novas regras",
        tools: ["Excel", "Confluence"],
      },
      {
        notation: "MATRIX",
        name: "Matriz RASCI",
        nameEn: "RASCI Matrix",
        description: "RACI + Support (Suporte)",
        useCase: "Governança de mudanças",
        tools: ["Excel", "Confluence"],
      },
      {
        notation: "MATRIX",
        name: "Matriz de Responsabilidades",
        nameEn: "Responsibility Assignment Matrix",
        description: "Matriz genérica de responsabilidades",
        useCase: "Governança de processos",
        tools: ["Excel", "Confluence"],
      },
      {
        notation: "MATRIX",
        name: "Matriz de Decisão",
        nameEn: "Decision Matrix",
        description: "Critérios x Alternativas com pontuação",
        useCase: "Escolher tecnologia para novo módulo",
        tools: ["Excel", "Miro"],
      },
      {
        notation: "TREE",
        name: "Árvore de Decisão",
        nameEn: "Decision Tree",
        description: "Estrutura hierárquica de decisões",
        useCase: "Lógica de classificação de risco",
        tools: ["draw.io", "Miro"],
      },
      {
        notation: "MATRIX",
        name: "Tabela de Decisão",
        nameEn: "Decision Table",
        description: "Mapeia combinações de condições para ações",
        useCase: "Documentar regras de negócio complexas",
        tools: ["Excel", "Confluence", "DMN"],
      },
      {
        notation: "DMN",
        name: "DMN - DRD",
        nameEn: "Decision Requirements Diagram",
        description: "Dependências entre decisões (DMN)",
        useCase: "Modelar decisões compostas no RULEX",
        tools: ["Camunda Modeler", "Trisotech"],
      },
      {
        notation: "DMN",
        name: "DMN - Tabela de Decisão",
        nameEn: "DMN Decision Table",
        description: "Tabela de decisão executável (DMN)",
        useCase: "Regras estruturadas executáveis",
        tools: ["Camunda Modeler"],
      },
      {
        notation: "DMN",
        name: "DMN - Expressão FEEL",
        nameEn: "DMN FEEL Expression",
        description: "Friendly Enough Expression Language",
        useCase: "Expressões de cálculo de score",
        tools: ["Camunda Modeler"],
      },
      {
        notation: "PROCESS",
        name: "Diagrama de Regras de Negócio",
        nameEn: "Business Rules Diagram",
        description: "Representação visual de regras",
        useCase: "Documentar lógica do motor de regras",
        tools: ["draw.io"],
      },
      {
        notation: "PROCESS",
        name: "Event Storming - Big Picture",
        nameEn: "Event Storming (Big Picture)",
        description: "Workshop colaborativo: descobrir eventos de domínio",
        useCase: "Descobrir eventos: TransactionReceived, FraudDetected",
        tools: ["Miro", "Mural", "FigJam"],
      },
      {
        notation: "PROCESS",
        name: "Event Storming - Process Level",
        nameEn: "Event Storming (Process Level)",
        description: "Detalhamento de processos específicos",
        useCase: "Modelar fluxo de avaliação de regras",
        tools: ["Miro", "Mural"],
      },
      {
        notation: "PROCESS",
        name: "Event Storming - Design Level",
        nameEn: "Event Storming (Design Level)",
        description: "Nível de implementação com agregados e comandos",
        useCase: "Design técnico de bounded contexts",
        tools: ["Miro", "Mural"],
      },
      {
        notation: "PROCESS",
        name: "Timeline de Processo",
        nameEn: "Process Timeline",
        description: "Linha do tempo com marcos e durações",
        useCase: "SLA de processamento de transações",
        tools: ["Miro", "Lucidchart"],
      },
      {
        notation: "PROCESS",
        name: "Diagrama de Exceções",
        nameEn: "Exception Flow Diagram",
        description: "Fluxos de tratamento de exceções",
        useCase: "Documentar fallbacks e recuperação de erros",
        tools: ["draw.io"],
      },
      {
        notation: "MATRIX",
        name: "Matriz GO/NO-GO",
        nameEn: "GO/NO-GO Matrix",
        description: "Critérios para aprovação de release/operação",
        useCase: "Checklist de deploy em produção",
        tools: ["Excel", "Confluence"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 2: UML Completo (17 tipos)
  // ============================================================
  {
    id: "uml",
    notation: "UML",
    title: "UML (Unified Modeling Language)",
    description: "Notação padrão para modelagem OO",
    diagrams: [
      // Estruturais (7)
      {
        notation: "UML",
        name: "Diagrama de Classes",
        nameEn: "Class Diagram",
        description: "Classes, atributos, métodos e relacionamentos",
        useCase: "Modelar entidades do RULEX: Rule, Condition, Transaction",
        tools: ["PlantUML", "Enterprise Architect", "IntelliJ"],
      },
      {
        notation: "UML",
        name: "Diagrama de Objetos",
        nameEn: "Object Diagram",
        description: "Instâncias de classes em momento específico",
        useCase: "Snapshot de uma regra e suas condições em runtime",
        tools: ["PlantUML", "Enterprise Architect"],
      },
      {
        notation: "UML",
        name: "Diagrama de Pacotes",
        nameEn: "Package Diagram",
        description: "Organização de classes em pacotes",
        useCase: "Estrutura do backend: com.rulex.controller, .service, .entity",
        tools: ["PlantUML", "IntelliJ"],
      },
      {
        notation: "UML",
        name: "Diagrama de Componentes",
        nameEn: "Component Diagram",
        description: "Componentes do sistema e dependências",
        useCase: "Módulos do backend: Controller, Service, Repository",
        tools: ["PlantUML", "draw.io"],
      },
      {
        notation: "UML",
        name: "Diagrama de Estrutura Composta",
        nameEn: "Composite Structure Diagram",
        description: "Estrutura interna de um classificador",
        useCase: "Detalhamento interno do ExpressionEvaluator",
        tools: ["Enterprise Architect"],
      },
      {
        notation: "UML",
        name: "Diagrama de Implantação",
        nameEn: "Deployment Diagram",
        description: "Distribuição física de artefatos em nós",
        useCase: "Deploy: Frontend (CDN), Backend (K8s), DB (RDS)",
        tools: ["PlantUML", "draw.io"],
      },
      {
        notation: "UML",
        name: "Diagrama de Perfil",
        nameEn: "Profile Diagram",
        description: "Extensões e estereótipos customizados para UML",
        useCase: "Definir estereótipos para domínio de fraude",
        tools: ["Enterprise Architect"],
      },
      // Comportamentais (10)
      {
        notation: "UML",
        name: "Diagrama de Casos de Uso",
        nameEn: "Use Case Diagram",
        description: "Atores e casos de uso do sistema",
        useCase: "Funcionalidades: Criar Regra, Analisar Transação",
        tools: ["PlantUML", "draw.io"],
      },
      {
        notation: "UML",
        name: "Diagrama de Atividade",
        nameEn: "Activity Diagram",
        description: "Fluxo de controle de atividades",
        useCase: "Algoritmo de avaliação de regras com fork/join",
        tools: ["PlantUML", "draw.io"],
      },
      {
        notation: "UML",
        name: "Diagrama de Máquina de Estados",
        nameEn: "State Machine Diagram",
        description: "Estados e transições de uma entidade",
        useCase: "Ciclo de vida: DRAFT → ACTIVE → DEPRECATED",
        tools: ["PlantUML", "Mermaid"],
      },
      {
        notation: "UML",
        name: "Diagrama de Sequência",
        nameEn: "Sequence Diagram",
        description: "Interação entre objetos ao longo do tempo",
        useCase: "Fluxo: Controller → Service → Repository → DB",
        tools: ["PlantUML", "Mermaid", "SequenceDiagram.org"],
      },
      {
        notation: "UML",
        name: "Diagrama de Comunicação",
        nameEn: "Communication Diagram",
        description: "Interação com foco em estrutura",
        useCase: "Mensagens entre componentes do motor",
        tools: ["PlantUML", "Enterprise Architect"],
      },
      {
        notation: "UML",
        name: "Diagrama de Tempo",
        nameEn: "Timing Diagram",
        description: "Mudança de estado ao longo do tempo",
        useCase: "SLA de resposta do /analyze ao longo de 24h",
        tools: ["Enterprise Architect"],
      },
      {
        notation: "UML",
        name: "Diagrama de Visão Geral de Interação",
        nameEn: "Interaction Overview Diagram",
        description: "Combina atividade e sequência",
        useCase: "Fluxo completo mostrando alternativas",
        tools: ["Enterprise Architect"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 3: C4 Model (6 tipos)
  // ============================================================
  {
    id: "c4",
    notation: "C4",
    title: "C4 Model",
    description: "Context, Containers, Components, Code",
    diagrams: [
      {
        notation: "C4",
        name: "C4 - Contexto",
        nameEn: "C4 System Context",
        description: "Sistema no contexto de usuários e sistemas externos",
        useCase: "RULEX e suas integrações: Gateway, Banco Emissor",
        tools: ["Structurizr", "PlantUML C4", "draw.io"],
      },
      {
        notation: "C4",
        name: "C4 - Contêineres",
        nameEn: "C4 Container",
        description: "Aplicações e datastores que compõem o sistema",
        useCase: "React, Spring Boot, PostgreSQL, Redis",
        tools: ["Structurizr", "PlantUML C4"],
      },
      {
        notation: "C4",
        name: "C4 - Componentes",
        nameEn: "C4 Component",
        description: "Componentes dentro de um contêiner",
        useCase: "Controllers, Services, Repositories do backend",
        tools: ["Structurizr", "PlantUML C4"],
      },
      {
        notation: "C4",
        name: "C4 - Código",
        nameEn: "C4 Code",
        description: "Classes/código (opcional, usa UML)",
        useCase: "Detalhe do ExpressionEvaluator e AST",
        tools: ["PlantUML", "IDE diagrams"],
      },
      {
        notation: "C4",
        name: "C4 - Dinâmico",
        nameEn: "C4 Dynamic",
        description: "Fluxos/sequências entre componentes",
        useCase: "Fluxo de autenticação e análise",
        tools: ["Structurizr"],
      },
      {
        notation: "C4",
        name: "C4 - Deployment",
        nameEn: "C4 Deployment",
        description: "Mapeamento para infraestrutura física",
        useCase: "Deploy em ambientes AWS/Azure",
        tools: ["Structurizr"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 4: Arquitetura & Padrões (50 tipos)
  // ============================================================
  {
    id: "arquitetura",
    notation: "ARCHIMATE",
    title: "Arquitetura & Padrões",
    description: "Estilos arquiteturais, padrões e topologias",
    diagrams: [
      {
        notation: "ARCHIMATE",
        name: "Arquitetura em Camadas",
        nameEn: "Layered Architecture",
        description: "Organização em camadas: Presentation, Business, Data",
        useCase: "Estrutura do backend RULEX seguindo Clean Architecture",
        tools: ["draw.io", "Lucidchart"],
      },
      {
        notation: "ARCHIMATE",
        name: "Arquitetura Hexagonal",
        nameEn: "Hexagonal (Ports & Adapters)",
        description: "Domínio no centro, ports e adapters",
        useCase: "Isolar lógica de negócio de frameworks e I/O",
        tools: ["draw.io", "PlantUML"],
      },
      {
        notation: "ARCHIMATE",
        name: "Clean Architecture",
        nameEn: "Clean Architecture",
        description: "Círculos concêntricos de dependência",
        useCase: "Princípio de dependência invertida no RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Onion Architecture",
        nameEn: "Onion Architecture",
        description: "Camadas concêntricas similar a Clean",
        useCase: "Variante de arquitetura limpa",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Arquitetura de Microserviços",
        nameEn: "Microservices Architecture",
        description: "Serviços independentes e suas comunicações",
        useCase: "Se RULEX evoluir: Rules, Transactions, Audit",
        tools: ["draw.io", "Lucidchart"],
      },
      {
        notation: "ARCHIMATE",
        name: "Monolito Modular",
        nameEn: "Modular Monolith",
        description: "Monolito com forte separação modular",
        useCase: "Arquitetura atual do RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Topologia de Serviços",
        nameEn: "Service Topology",
        description: "Visão física/lógica da distribuição dos serviços",
        useCase: "Deployment multi-região com failover",
        tools: ["draw.io", "Cloudcraft"],
      },
      {
        notation: "ARCHIMATE",
        name: "Landscape de Sistemas",
        nameEn: "System Landscape",
        description: "Visão geral de todos os sistemas do ecossistema",
        useCase: "RULEX + todos os sistemas integrados",
        tools: ["draw.io", "Lucidchart"],
      },
      {
        notation: "ARCHIMATE",
        name: "Landscape de Integração",
        nameEn: "Integration Landscape",
        description: "Todas as integrações do ecossistema",
        useCase: "RULEX + APIs consumidas/expostas",
        tools: ["draw.io", "Lucidchart"],
      },
      {
        notation: "ARCHIMATE",
        name: "API Gateway Architecture",
        nameEn: "API Gateway Architecture",
        description: "Padrão de gateway unificado para APIs",
        useCase: "Centralizar autenticação e rate limiting",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "BFF (Backend for Frontend)",
        nameEn: "BFF Pattern",
        description: "Backend específico para cada tipo de cliente",
        useCase: "API otimizada para web vs mobile",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Service Mesh",
        nameEn: "Service Mesh Diagram",
        description: "Camada de infraestrutura para comunicação entre serviços",
        useCase: "Istio/Linkerd para observabilidade",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Arquitetura Event-Driven",
        nameEn: "Event-Driven Architecture",
        description: "Produtores, consumidores e brokers de eventos",
        useCase: "Se RULEX usar Kafka: FraudDetected → Notification",
        tools: ["draw.io", "Confluent"],
      },
      {
        notation: "ARCHIMATE",
        name: "Topologia Pub/Sub",
        nameEn: "Pub/Sub Topology",
        description: "Padrão de publicação e assinatura",
        useCase: "Notificações em tempo real via WebSocket",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "CQRS",
        nameEn: "CQRS Diagram",
        description: "Command Query Responsibility Segregation",
        useCase: "Separar leitura e escrita de regras",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Event Sourcing",
        nameEn: "Event Sourcing Diagram",
        description: "Estado como sequência de eventos",
        useCase: "Audit trail completo de mudanças em regras",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Saga - Orquestração",
        nameEn: "Saga (Orchestration)",
        description: "Coordenador central de transações distribuídas",
        useCase: "Rollback de aprovação se notificação falhar",
        tools: ["draw.io", "PlantUML"],
      },
      {
        notation: "ARCHIMATE",
        name: "Saga - Coreografia",
        nameEn: "Saga (Choreography)",
        description: "Eventos disparando próximas etapas",
        useCase: "Transações distribuídas sem orquestrador",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Outbox Pattern",
        nameEn: "Outbox Pattern",
        description: "Publicar eventos de forma transacional",
        useCase: "Garantir entrega de eventos ao Kafka",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Inbox Pattern",
        nameEn: "Inbox Pattern",
        description: "Consumir eventos de forma idempotente",
        useCase: "Evitar processamento duplicado",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Strangler Fig",
        nameEn: "Strangler Fig Migration",
        description: "Migração gradual de sistema legado",
        useCase: "Migrar funcionalidades para nova arquitetura",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Anti-Corruption Layer (ACL)",
        nameEn: "ACL Diagram",
        description: "Camada de tradução entre sistemas",
        useCase: "Isolar RULEX de mudanças em APIs externas",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Rate Limiting",
        nameEn: "Rate Limiting Diagram",
        description: "Controle de taxa de requisições",
        useCase: "Proteger API de sobrecarga",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Idempotência",
        nameEn: "Idempotency Flow",
        description: "Garantir que operações são idempotentes",
        useCase: "Reprocessamento seguro de transações",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Retry/Timeout/Circuit Breaker",
        nameEn: "Resilience Patterns",
        description: "Padrões de resiliência",
        useCase: "Proteger RULEX de falhas em serviços externos",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Bulkhead Pattern",
        nameEn: "Bulkhead Pattern",
        description: "Isolamento de recursos por domínio",
        useCase: "Pools de conexão separados por tipo de operação",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Failover",
        nameEn: "Failover Diagram",
        description: "Alternância automática para backup",
        useCase: "HA do RULEX com réplicas",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Fluxo de Tráfego",
        nameEn: "Traffic Flow Diagram",
        description: "Roteamento de tráfego L4/L7",
        useCase: "Balanceamento e roteamento de requisições",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Load Balancing",
        nameEn: "Load Balancing Diagram",
        description: "Distribuição de carga entre instâncias",
        useCase: "ALB/NLB para o RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Blue/Green Deployment",
        nameEn: "Blue-Green Deployment",
        description: "Dois ambientes idênticos para zero-downtime",
        useCase: "Deploy sem downtime do RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Canary Deployment",
        nameEn: "Canary Deployment",
        description: "Rollout gradual para subset de tráfego",
        useCase: "Testar nova versão com 5% do tráfego",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Rolling Update",
        nameEn: "Rolling Update Diagram",
        description: "Atualização gradual instância por instância",
        useCase: "Deploy progressivo em K8s",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Feature Flags",
        nameEn: "Feature Flags Flow",
        description: "Controle de features via flags",
        useCase: "Habilitar/desabilitar funcionalidades sem deploy",
        tools: ["draw.io"],
      },
      // Continuando com mais padrões arquiteturais...
      {
        notation: "ARCHIMATE",
        name: "Diagrama de Dependências",
        nameEn: "Dependency Diagram",
        description: "Grafo de dependências entre módulos/libs",
        useCase: "Visualizar dependências do projeto",
        tools: ["IntelliJ", "draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Call Graph",
        nameEn: "Call Graph",
        description: "Grafo de chamadas de funções",
        useCase: "Analisar fluxo de execução",
        tools: ["IDE profiler"],
      },
      {
        notation: "ARCHIMATE",
        name: "Control Flow Graph (CFG)",
        nameEn: "Control Flow Graph",
        description: "Grafo de fluxo de controle",
        useCase: "Análise estática de código",
        tools: ["Compiler tools"],
      },
      {
        notation: "ARCHIMATE",
        name: "Data Dependency Graph (DDG)",
        nameEn: "Data Dependency Graph",
        description: "Grafo de dependências de dados",
        useCase: "Otimização de queries",
        tools: ["Query planner"],
      },
      {
        notation: "ARCHIMATE",
        name: "ADR Map",
        nameEn: "Architecture Decision Record Map",
        description: "Mapa de decisões arquiteturais",
        useCase: "Documentar escolhas técnicas",
        tools: ["Markdown", "Confluence"],
      },
      {
        notation: "ARCHIMATE",
        name: "Diagrama de Contexto",
        nameEn: "Context Diagram",
        description: "Sistema e seus vizinhos externos",
        useCase: "Visão de alto nível do RULEX",
        tools: ["draw.io"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 5: Dados Postgres (20 tipos)
  // ============================================================
  {
    id: "dados_postgres",
    notation: "ER",
    title: "Dados - PostgreSQL",
    description: "Modelagem relacional, schemas, índices, replicação",
    diagrams: [
      {
        notation: "ER",
        name: "DER - Entidades e Relacionamentos",
        nameEn: "Entity-Relationship Diagram (ERD)",
        description: "Modelo conceitual de dados",
        useCase: "Modelar Rule, Condition, Transaction, User",
        tools: ["dbdiagram.io", "Draw.io", "ERDPlus"],
      },
      {
        notation: "ER",
        name: "DER - Crow's Foot",
        nameEn: "Crow's Foot Notation",
        description: "Notação popular de cardinalidade",
        useCase: "Documentar relacionamentos 1:N, M:N",
        tools: ["dbdiagram.io", "Lucidchart"],
      },
      {
        notation: "ER",
        name: "DER - Pé de Galinha (Barker)",
        nameEn: "Barker Notation",
        description: "Notação usada em Oracle Designer",
        useCase: "Modelos Oracle-centric",
        tools: ["Oracle Data Modeler"],
      },
      {
        notation: "ER",
        name: "DER - Chen",
        nameEn: "Chen Notation",
        description: "Notação clássica de Peter Chen",
        useCase: "Modelos conceituais acadêmicos",
        tools: ["draw.io"],
      },
      {
        notation: "ER",
        name: "Modelo Lógico Relacional",
        nameEn: "Logical Data Model",
        description: "Tabelas, colunas, PKs, FKs",
        useCase: "Mapear entidades para tabelas PostgreSQL",
        tools: ["dbdiagram.io", "pgModeler"],
      },
      {
        notation: "ER",
        name: "Modelo Físico (DDL)",
        nameEn: "Physical Data Model",
        description: "Schema com tipos, constraints, triggers",
        useCase: "Schema do RULEX com Flyway migrations",
        tools: ["pgModeler", "DBeaver"],
      },
      {
        notation: "ER",
        name: "Schema de Banco de Dados",
        nameEn: "Database Schema Diagram",
        description: "Visualização de schemas existentes",
        useCase: "Reverse engineer do banco RULEX",
        tools: ["DBeaver", "pgAdmin", "SchemaSpy"],
      },
      {
        notation: "ER",
        name: "Diagrama de Índices",
        nameEn: "Index Diagram",
        description: "Estratégia de índices e performance",
        useCase: "Otimizar queries de busca de regras",
        tools: ["pgAdmin", "PostgreSQL Explain"],
      },
      {
        notation: "ER",
        name: "Particionamento",
        nameEn: "Table Partitioning Diagram",
        description: "Estratégia de particionamento horizontal/vertical",
        useCase: "Particionar tabela de transações por data",
        tools: ["pgModeler", "draw.io"],
      },
      {
        notation: "ER",
        name: "Replicação Master-Replica",
        nameEn: "Master-Replica Replication",
        description: "Topologia de replicação",
        useCase: "HA do PostgreSQL com réplicas read-only",
        tools: ["draw.io"],
      },
      {
        notation: "ER",
        name: "Replicação Multi-Master",
        nameEn: "Multi-Master Replication",
        description: "Replicação bidirecional",
        useCase: "Ambientes geograficamente distribuídos",
        tools: ["draw.io"],
      },
      {
        notation: "ER",
        name: "Sharding",
        nameEn: "Database Sharding Diagram",
        description: "Distribuição horizontal de dados",
        useCase: "Escalar leitura de transações",
        tools: ["draw.io"],
      },
      {
        notation: "ER",
        name: "Modelo Star Schema",
        nameEn: "Star Schema",
        description: "Fatos e dimensões (Data Warehouse)",
        useCase: "Analytics: FactTransaction, DimRule, DimTime",
        tools: ["dbdiagram.io", "PowerBI"],
      },
      {
        notation: "ER",
        name: "Modelo Snowflake Schema",
        nameEn: "Snowflake Schema",
        description: "Dimensões normalizadas",
        useCase: "DW com dimensões hierárquicas",
        tools: ["dbdiagram.io", "Tableau"],
      },
      {
        notation: "ER",
        name: "Data Lineage",
        nameEn: "Data Lineage Diagram",
        description: "Rastreamento de origem e transformações",
        useCase: "De onde vem o campo 'riskScore'?",
        tools: ["Apache Atlas", "Collibra"],
      },
      {
        notation: "ER",
        name: "Data Flow - Dados",
        nameEn: "Data Flow Diagram (Data-centric)",
        description: "Fluxo de dados entre sistemas",
        useCase: "Gateway → RULEX → DW → BI",
        tools: ["draw.io"],
      },
      {
        notation: "ER",
        name: "Diagrama de Migração",
        nameEn: "Migration Diagram",
        description: "Plano de migração de schema",
        useCase: "Flyway: V1 → V2 → V3 com rollback",
        tools: ["draw.io"],
      },
      {
        notation: "ER",
        name: "Backup & Recovery",
        nameEn: "Backup & Recovery Diagram",
        description: "Estratégia de backup e restore",
        useCase: "pg_dump diário + WAL archiving",
        tools: ["draw.io"],
      },
      {
        notation: "ER",
        name: "Diagrama de Views",
        nameEn: "Views Diagram",
        description: "Materialized e regular views",
        useCase: "Views para dashboard de métricas",
        tools: ["pgAdmin"],
      },
      {
        notation: "ER",
        name: "Diagrama de Triggers/Procedures",
        nameEn: "Triggers & Stored Procedures",
        description: "Lógica armazenada no banco",
        useCase: "Trigger para audit log automático",
        tools: ["pgAdmin", "DBeaver"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 6: Dados Redis (15 tipos)
  // ============================================================
  {
    id: "dados_redis",
    notation: "GRAPH",
    title: "Dados - Redis",
    description: "Estratégias de cache, invalidação, pub/sub, streams",
    diagrams: [
      {
        notation: "GRAPH",
        name: "Estratégia de Cache",
        nameEn: "Cache Strategy Diagram",
        description: "Cache-aside, Read-through, Write-through, Write-behind",
        useCase: "Cachear regras ativas no Redis",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Cache Invalidation",
        nameEn: "Cache Invalidation Flow",
        description: "Estratégias de invalidação (TTL, event-based)",
        useCase: "Invalidar cache ao editar regra",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Cache Warming",
        nameEn: "Cache Warming Diagram",
        description: "Pré-carregar cache no startup",
        useCase: "Popular cache de regras ao reiniciar",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Replicação Redis",
        nameEn: "Redis Replication",
        description: "Master + réplicas read-only",
        useCase: "HA do cache com réplicas",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Redis Sentinel",
        nameEn: "Redis Sentinel Topology",
        description: "Monitoramento e failover automático",
        useCase: "Alta disponibilidade do Redis",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Redis Cluster",
        nameEn: "Redis Cluster Diagram",
        description: "Sharding automático",
        useCase: "Escalar cache horizontalmente",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Pub/Sub - Redis",
        nameEn: "Redis Pub/Sub Diagram",
        description: "Padrão publicação/assinatura",
        useCase: "Notificações de mudanças em regras",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Redis Streams",
        nameEn: "Redis Streams Diagram",
        description: "Event streaming com consumer groups",
        useCase: "Stream de eventos de transação",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Rate Limiting - Redis",
        nameEn: "Redis Rate Limiting",
        description: "Sliding window, fixed window, token bucket",
        useCase: "Rate limit por usuário/API key",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Distributed Lock - Redis",
        nameEn: "Redis Distributed Lock",
        description: "Redlock algorithm para locks",
        useCase: "Evitar race conditions em deploys",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Session Store - Redis",
        nameEn: "Redis Session Store",
        description: "Armazenamento de sessões",
        useCase: "Sessões de usuário do RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Leaderboard - Redis",
        nameEn: "Redis Sorted Sets Leaderboard",
        description: "Ranking com sorted sets",
        useCase: "Top 10 regras mais acionadas",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Diagrama de Estruturas de Dados",
        nameEn: "Redis Data Structures Diagram",
        description: "String, Hash, List, Set, Sorted Set",
        useCase: "Escolher estrutura certa para cada caso",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Redis Persistence",
        nameEn: "Redis Persistence Diagram",
        description: "RDB snapshots vs AOF append-only",
        useCase: "Estratégia de persistência",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Redis Multi-Tenancy",
        nameEn: "Redis Multi-Tenancy Pattern",
        description: "Isolamento por tenant (key prefixes, databases)",
        useCase: "Cache isolado por cliente",
        tools: ["draw.io"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 7: Dados Neo4j / Grafos (10 tipos)
  // ============================================================
  {
    id: "dados_neo4j",
    notation: "GRAPH",
    title: "Dados - Neo4j & Grafos",
    description: "Property graphs, traversals, ontologias",
    diagrams: [
      {
        notation: "GRAPH",
        name: "Property Graph Model",
        nameEn: "Property Graph Model",
        description: "Nós e relacionamentos com propriedades",
        useCase: "Modelar grafo de relacionamentos entre entidades",
        tools: ["Neo4j Browser", "Arrows.app"],
      },
      {
        notation: "GRAPH",
        name: "Cypher Query Flow",
        nameEn: "Cypher Query Visualization",
        description: "Visualização de consultas Cypher",
        useCase: "Documentar traversals complexos",
        tools: ["Neo4j Browser"],
      },
      {
        notation: "GRAPH",
        name: "Grafo de Conhecimento",
        nameEn: "Knowledge Graph",
        description: "Ontologia com entidades e relações semânticas",
        useCase: "Conectar fraudes, clientes, dispositivos",
        tools: ["Neo4j", "GraphDB"],
      },
      {
        notation: "GRAPH",
        name: "Diagrama de Traversal",
        nameEn: "Graph Traversal Diagram",
        description: "Algoritmos de busca (BFS, DFS, shortest path)",
        useCase: "Detectar padrões de fraude em rede",
        tools: ["Neo4j", "draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Ontologia OWL",
        nameEn: "OWL Ontology Diagram",
        description: "Web Ontology Language para semântica",
        useCase: "Ontologia de domínio de fraude",
        tools: ["Protégé", "WebVOWL"],
      },
      {
        notation: "GRAPH",
        name: "RDF Triple Store",
        nameEn: "RDF Triple Diagram",
        description: "Subject–Predicate–Object triples",
        useCase: "Linked data para integração",
        tools: ["Protégé", "GraphDB"],
      },
      {
        notation: "GRAPH",
        name: "SHACL Shapes",
        nameEn: "SHACL Constraints Diagram",
        description: "Shapes Constraint Language para validação",
        useCase: "Validar estrutura do grafo",
        tools: ["TopBraid"],
      },
      {
        notation: "GRAPH",
        name: "Grafo Social",
        nameEn: "Social Network Graph",
        description: "Rede social de usuários/conexões",
        useCase: "Detectar contas conectadas suspeitas",
        tools: ["Neo4j", "Gephi"],
      },
      {
        notation: "GRAPH",
        name: "Grafo de Dependências",
        nameEn: "Dependency Graph",
        description: "Dependências entre componentes/módulos",
        useCase: "Visualizar dependências do projeto",
        tools: ["Neo4j", "Graphviz"],
      },
      {
        notation: "GRAPH",
        name: "Diagrama de Replicação de Grafo",
        nameEn: "Graph Replication Diagram",
        description: "Causal clustering do Neo4j",
        useCase: "HA do Neo4j com réplicas",
        tools: ["draw.io"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 8: Frontend React / UX (12 tipos)
  // ============================================================
  {
    id: "frontend",
    notation: "UML",
    title: "Frontend React & UX",
    description: "Component trees, state, atomic design, protótipos",
    diagrams: [
      {
        notation: "UML",
        name: "Árvore de Componentes React",
        nameEn: "React Component Tree",
        description: "Hierarquia de componentes",
        useCase: "App → RulesPage → RuleFormDialog → ConditionBuilder",
        tools: ["React DevTools", "draw.io"],
      },
      {
        notation: "UML",
        name: "Props & Data Flow",
        nameEn: "Props Flow Diagram",
        description: "Fluxo de props entre componentes",
        useCase: "Como ruleData flui da API até a UI",
        tools: ["draw.io"],
      },
      {
        notation: "UML",
        name: "State Management",
        nameEn: "State Management Diagram",
        description: "Estado global (Redux/Zustand) e local",
        useCase: "Estado de autenticação e filtros",
        tools: ["Redux DevTools", "draw.io"],
      },
      {
        notation: "UML",
        name: "Diagrama de Rotas",
        nameEn: "Routing Diagram",
        description: "Estrutura de rotas da SPA",
        useCase: "Rotas do RULEX: /login, /rules, /analytics",
        tools: ["draw.io"],
      },
      {
        notation: "PROCESS",
        name: "Atomic Design",
        nameEn: "Atomic Design System",
        description: "Atoms → Molecules → Organisms → Templates → Pages",
        useCase: "Estrutura do design system do RULEX",
        tools: ["Figma", "Storybook"],
      },
      {
        notation: "UML",
        name: "Diagrama de Hooks",
        nameEn: "React Hooks Diagram",
        description: "Lifecycle e hooks customizados",
        useCase: "useRules, useAuth, useDebounce",
        tools: ["draw.io"],
      },
      {
        notation: "UML",
        name: "Context API",
        nameEn: "Context API Diagram",
        description: "Contextos e providers",
        useCase: "AuthContext, ThemeContext",
        tools: ["draw.io"],
      },
      {
        notation: "PROCESS",
        name: "Wireframe",
        nameEn: "Wireframe",
        description: "Esboço de baixa fidelidade da UI",
        useCase: "Wireframe da tela de criação de regra",
        tools: ["Figma", "Balsamiq"],
      },
      {
        notation: "PROCESS",
        name: "Mockup",
        nameEn: "Mockup",
        description: "Design de média/alta fidelidade",
        useCase: "Mockup visual do RULEX",
        tools: ["Figma", "Sketch"],
      },
      {
        notation: "PROCESS",
        name: "Protótipo Interativo",
        nameEn: "Interactive Prototype",
        description: "Protótipo clicável com interações",
        useCase: "Protótipo do fluxo de criação de regra",
        tools: ["Figma", "InVision"],
      },
      {
        notation: "GRAPH",
        name: "User Flow",
        nameEn: "User Flow Diagram",
        description: "Fluxo de navegação do usuário",
        useCase: "Caminho do login até aprovação de regra",
        tools: ["Figma", "Miro"],
      },
      {
        notation: "GRAPH",
        name: "Mapa de Acessibilidade",
        nameEn: "Accessibility Map",
        description: "Pontos de conformidade WCAG",
        useCase: "Checklist A11y do RULEX",
        tools: ["Figma", "Confluence"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 9: DevOps / Infraestrutura (15 tipos)
  // ============================================================
  {
    id: "devops",
    notation: "ARCHIMATE",
    title: "DevOps & Infraestrutura",
    description: "CI/CD, K8s, observabilidade, SLO",
    diagrams: [
      {
        notation: "ARCHIMATE",
        name: "Pipeline CI/CD",
        nameEn: "CI/CD Pipeline Diagram",
        description: "Build → Test → Deploy",
        useCase: "GitHub Actions do RULEX: lint → test → build → deploy",
        tools: ["draw.io", "Lucidchart"],
      },
      {
        notation: "ARCHIMATE",
        name: "GitFlow",
        nameEn: "GitFlow Diagram",
        description: "Branches: main, develop, feature, hotfix",
        useCase: "Estratégia de branching do RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Trunk-Based Development",
        nameEn: "Trunk-Based Development",
        description: "Main única com feature flags",
        useCase: "Alternative branching strategy",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Diagrama de Infraestrutura",
        nameEn: "Infrastructure Diagram",
        description: "VPCs, subnets, security groups",
        useCase: "Topologia AWS/Azure do RULEX",
        tools: ["Cloudcraft", "draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Kubernetes Architecture",
        nameEn: "Kubernetes Diagram",
        description: "Pods, Services, Ingress, ConfigMaps",
        useCase: "Deploy do RULEX em K8s",
        tools: ["draw.io", "k8sviz"],
      },
      {
        notation: "ARCHIMATE",
        name: "Helm Chart Structure",
        nameEn: "Helm Chart Diagram",
        description: "Templates e values",
        useCase: "Estrutura do chart do RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Service Mesh - Istio",
        nameEn: "Istio Service Mesh",
        description: "VirtualServices, DestinationRules, Gateways",
        useCase: "Observabilidade e traffic management",
        tools: ["Kiali", "draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Observability Stack",
        nameEn: "Observability Architecture",
        description: "Logs, Metrics, Traces (Prometheus, Grafana, Jaeger)",
        useCase: "Stack de observabilidade do RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Distributed Tracing",
        nameEn: "Distributed Tracing Diagram",
        description: "Spans e traces distribuídos",
        useCase: "Rastrear request através de microserviços",
        tools: ["Jaeger UI", "Zipkin"],
      },
      {
        notation: "ARCHIMATE",
        name: "Logging Architecture",
        nameEn: "Logging Architecture",
        description: "Coleta, agregação, indexação de logs",
        useCase: "ELK Stack: Elasticsearch, Logstash, Kibana",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Metrics & Alerting",
        nameEn: "Metrics & Alerting Diagram",
        description: "Prometheus, AlertManager, Grafana",
        useCase: "Dashboards e alertas do RULEX",
        tools: ["Grafana", "draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "SLO/SLI/SLA",
        nameEn: "SLO/SLI/SLA Diagram",
        description: "Service Level Objectives e indicadores",
        useCase: "SLO: 99.9% uptime, p99 < 500ms",
        tools: ["draw.io", "Confluence"],
      },
      {
        notation: "PROCESS",
        name: "Incident Timeline",
        nameEn: "Incident Timeline",
        description: "Linha do tempo de incidente",
        useCase: "Post-mortem de outage",
        tools: ["Miro", "Confluence"],
      },
      {
        notation: "ARCHIMATE",
        name: "Disaster Recovery Plan",
        nameEn: "DR Plan Diagram",
        description: "RPO, RTO, backup strategy",
        useCase: "Plano de recuperação de desastres",
        tools: ["draw.io"],
      },
      {
        notation: "ARCHIMATE",
        name: "Network Topology",
        nameEn: "Network Topology Diagram",
        description: "VPCs, peering, VPN, Direct Connect",
        useCase: "Topologia de rede da infra",
        tools: ["Cloudcraft", "draw.io"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 10: Segurança (20 tipos)
  // ============================================================
  {
    id: "seguranca",
    notation: "GRAPH",
    title: "Segurança",
    description: "Threat modeling, OAuth, RBAC, PII flows",
    diagrams: [
      {
        notation: "GRAPH",
        name: "Threat Model",
        nameEn: "Threat Model Diagram",
        description: "DFD + trust boundaries + threats",
        useCase: "Identificar ameaças ao RULEX",
        tools: ["Microsoft Threat Modeling Tool", "draw.io"],
      },
      {
        notation: "TREE",
        name: "STRIDE per Element",
        nameEn: "STRIDE Analysis",
        description: "Spoofing, Tampering, Repudiation, Info Disclosure, DoS, Elevation",
        useCase: "Avaliar ameaças em cada componente",
        tools: ["draw.io"],
      },
      {
        notation: "TREE",
        name: "Attack Tree",
        nameEn: "Attack Tree",
        description: "Árvore de possíveis vetores de ataque",
        useCase: "Como um atacante pode comprometer o RULEX",
        tools: ["draw.io", "AttackTree+"],
      },
      {
        notation: "GRAPH",
        name: "Security Architecture",
        nameEn: "Security Architecture Diagram",
        description: "Camadas de defesa (defense in depth)",
        useCase: "WAF → API Gateway → Auth → Backend → DB",
        tools: ["draw.io"],
      },
      {
        notation: "PROCESS",
        name: "Fluxo de Autenticação",
        nameEn: "Authentication Flow",
        description: "Login, JWT, session management",
        useCase: "Fluxo de login do RULEX com JWT",
        tools: ["draw.io", "Mermaid"],
      },
      {
        notation: "PROCESS",
        name: "OAuth 2.0 Flow",
        nameEn: "OAuth 2.0 Flow Diagram",
        description: "Authorization Code, Implicit, Client Credentials",
        useCase: "Integração com identity provider externo",
        tools: ["draw.io"],
      },
      {
        notation: "PROCESS",
        name: "OpenID Connect",
        nameEn: "OIDC Flow Diagram",
        description: "OAuth 2.0 + camada de identidade",
        useCase: "SSO com Google/Azure AD",
        tools: ["draw.io"],
      },
      {
        notation: "PROCESS",
        name: "SAML Flow",
        nameEn: "SAML Authentication Flow",
        description: "SP → IdP → assertion",
        useCase: "Integração corporativa via SAML",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "RBAC - Controle de Acesso Baseado em Papéis",
        nameEn: "RBAC Diagram",
        description: "Users → Roles → Permissions",
        useCase: "Admin, Analyst, Viewer no RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "ABAC - Controle de Acesso Baseado em Atributos",
        nameEn: "ABAC Diagram",
        description: "Decisões baseadas em atributos contextuais",
        useCase: "Políticas dinâmicas de acesso",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Policy as Code",
        nameEn: "Policy as Code Diagram",
        description: "Políticas declarativas (OPA, Cedar)",
        useCase: "Políticas de autorização testáveis",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Zero Trust Architecture",
        nameEn: "Zero Trust Diagram",
        description: "Never trust, always verify",
        useCase: "Arquitetura zero trust do RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "DFD",
        name: "PII Data Flow",
        nameEn: "PII Data Flow Diagram",
        description: "Fluxo de dados pessoais (LGPD/GDPR)",
        useCase: "Rastrear PII através do sistema",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Encryption at Rest/Transit",
        nameEn: "Encryption Diagram",
        description: "TLS, encryption keys, KMS",
        useCase: "Estratégia de criptografia do RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Key Management",
        nameEn: "Key Management Diagram",
        description: "Geração, rotação, revogação de chaves",
        useCase: "AWS KMS, Azure Key Vault",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Secrets Management",
        nameEn: "Secrets Management Diagram",
        description: "HashiCorp Vault, AWS Secrets Manager",
        useCase: "Gerenciar credenciais e tokens",
        tools: ["draw.io"],
      },
      {
        notation: "MATRIX",
        name: "Matriz de Risco",
        nameEn: "Risk Matrix",
        description: "Probabilidade x Impacto",
        useCase: "Priorizar remediação de vulnerabilidades",
        tools: ["Excel", "Confluence"],
      },
      {
        notation: "GRAPH",
        name: "Security Incident Response",
        nameEn: "Incident Response Playbook",
        description: "Detecção → Contenção → Erradicação → Recuperação",
        useCase: "Playbook para breach de segurança",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Compliance Mapping",
        nameEn: "Compliance Mapping Diagram",
        description: "Controles → Requisitos (PCI-DSS, SOC2)",
        useCase: "Mapear controles para certificação",
        tools: ["Confluence", "Vanta"],
      },
      {
        notation: "GRAPH",
        name: "Supply Chain Security",
        nameEn: "Supply Chain Security Diagram",
        description: "Dependências, SBOMs, vulnerabilidades",
        useCase: "Rastrear vulnerabilidades em libs",
        tools: ["Snyk", "Dependabot"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 11: Qualidade (15 tipos)
  // ============================================================
  {
    id: "qualidade",
    notation: "GRAPH",
    title: "Qualidade",
    description: "Testes, confiabilidade, engenharia de qualidade",
    diagrams: [
      {
        notation: "GRAPH",
        name: "Pirâmide de Testes",
        nameEn: "Test Pyramid",
        description: "Unit → Integration → E2E",
        useCase: "Estratégia de testes do RULEX",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Test Coverage Map",
        nameEn: "Test Coverage Map",
        description: "Mapa de cobertura por módulo",
        useCase: "Identificar áreas sem testes",
        tools: ["Istanbul", "Codecov"],
      },
      {
        notation: "GRAPH",
        name: "Chaos Engineering",
        nameEn: "Chaos Experiment Diagram",
        description: "Injeção de falhas controlada",
        useCase: "Testar resiliência do RULEX",
        tools: ["Chaos Monkey", "Gremlin"],
      },
      {
        notation: "TREE",
        name: "Fault Tree Analysis (FTA)",
        nameEn: "Fault Tree Analysis",
        description: "Árvore de falhas até evento topo",
        useCase: "Análise de causa raiz de downtime",
        tools: ["draw.io"],
      },
      {
        notation: "MATRIX",
        name: "FMEA",
        nameEn: "Failure Mode and Effects Analysis",
        description: "Modos de falha x Severidade x Probabilidade",
        useCase: "Análise de modos de falha em deploy",
        tools: ["Excel", "Confluence"],
      },
      {
        notation: "GRAPH",
        name: "Mutation Testing",
        nameEn: "Mutation Testing Diagram",
        description: "Visualizar mutantes mortos/vivos",
        useCase: "Avaliar qualidade dos testes",
        tools: ["Stryker"],
      },
      {
        notation: "GRAPH",
        name: "Load Testing Strategy",
        nameEn: "Load Testing Diagram",
        description: "Padrões de carga: spike, soak, stress",
        useCase: "Planejar testes de carga no RULEX",
        tools: ["k6", "JMeter"],
      },
      {
        notation: "GRAPH",
        name: "Performance Baseline",
        nameEn: "Performance Baseline Diagram",
        description: "Benchmarks e SLAs de performance",
        useCase: "p50, p95, p99 do /analyze",
        tools: ["Grafana", "draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Capacity Planning",
        nameEn: "Capacity Planning Diagram",
        description: "Projeção de capacidade vs demanda",
        useCase: "Escalar RULEX para Black Friday",
        tools: ["Excel", "draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Diagrama de Dependabilidade",
        nameEn: "Dependability Diagram",
        description: "Reliability, Availability, Maintainability, Safety",
        useCase: "Análise RAMS do sistema",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Reliability Block Diagram (RBD)",
        nameEn: "RBD",
        description: "Blocos em série/paralelo",
        useCase: "Modelar redundância do sistema",
        tools: ["draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Error Budget",
        nameEn: "Error Budget Diagram",
        description: "SLO vs consumo do error budget",
        useCase: "Equilibrar velocidade e estabilidade",
        tools: ["Grafana", "Confluence"],
      },
      {
        notation: "GRAPH",
        name: "Test Data Management",
        nameEn: "Test Data Flow",
        description: "Geração, anonimização, refresh de dados de teste",
        useCase: "Estratégia de dados de teste",
        tools: ["draw.io"],
      },
      {
        notation: "MATRIX",
        name: "Traceability Matrix",
        nameEn: "Requirements Traceability Matrix",
        description: "Requirements → Test Cases",
        useCase: "Rastrear cobertura de requisitos",
        tools: ["Excel", "Jira"],
      },
      {
        notation: "GRAPH",
        name: "Regression Test Suite",
        nameEn: "Regression Test Suite Diagram",
        description: "Estrutura de testes de regressão",
        useCase: "Testes críticos executados em todo deploy",
        tools: ["Playwright", "Cypress"],
      },
    ],
  },

  // ============================================================
  // FAMÍLIA 12: Ciência da Computação Clássica (10 tipos)
  // ============================================================
  {
    id: "cs_classicos",
    notation: "OTHER",
    title: "CS Clássicos",
    description: "Modelos formais da ciência da computação",
    diagrams: [
      {
        notation: "GRAPH",
        name: "Autômato Finito (DFA/NFA)",
        nameEn: "Finite State Automaton",
        description: "Estados, transições, alfabeto",
        useCase: "Modelar parser de expressões",
        tools: ["JFLAP", "draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Autômato de Pilha (PDA)",
        nameEn: "Pushdown Automaton",
        description: "Autômato com stack",
        useCase: "Parser de linguagens context-free",
        tools: ["JFLAP"],
      },
      {
        notation: "GRAPH",
        name: "Máquina de Turing",
        nameEn: "Turing Machine",
        description: "Fita infinita, estados, transições",
        useCase: "Modelo computacional universal",
        tools: ["JFLAP", "draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Rede de Petri",
        nameEn: "Petri Net",
        description: "Places, transitions, tokens",
        useCase: "Modelar concorrência e recursos",
        tools: ["PIPE", "draw.io"],
      },
      {
        notation: "DFD",
        name: "DFD - Yourdon/DeMarco",
        nameEn: "Data Flow Diagram (Yourdon)",
        description: "Processos (círculos), fluxos (setas), armazenamentos (linhas paralelas)",
        useCase: "Análise estruturada de sistemas",
        tools: ["draw.io", "Visio"],
      },
      {
        notation: "DFD",
        name: "DFD - Gane–Sarson",
        nameEn: "Data Flow Diagram (Gane-Sarson)",
        description: "Processos (retângulos arredondados)",
        useCase: "Alternativa ao Yourdon",
        tools: ["draw.io", "Visio"],
      },
      {
        notation: "PROCESS",
        name: "IDEF0",
        nameEn: "IDEF0 Functional Modeling",
        description: "Inputs, Controls, Outputs, Mechanisms",
        useCase: "Modelagem funcional hierárquica",
        tools: ["Visio", "SmartDraw"],
      },
      {
        notation: "PROCESS",
        name: "IDEF3",
        nameEn: "IDEF3 Process Description",
        description: "Scenarios e object state transitions",
        useCase: "Captura de processos",
        tools: ["Visio"],
      },
      {
        notation: "GRAPH",
        name: "Parse Tree / AST",
        nameEn: "Abstract Syntax Tree",
        description: "Árvore sintática abstrata",
        useCase: "Representar estrutura de expressões do RULEX",
        tools: ["Graphviz", "draw.io"],
      },
      {
        notation: "GRAPH",
        name: "Grafo de Precedência",
        nameEn: "Precedence Graph",
        description: "Dependências de tarefas/operações",
        useCase: "Scheduling e análise de deadlock",
        tools: ["draw.io"],
      },
    ],
  },
];

export function getMassiveDiagramCount(): number {
  return MASSIVE_DIAGRAM_CATALOG.reduce(
    (sum, family) => sum + family.diagrams.length,
    0
  );
}
